- src/NotesLoaderBMS.cpp
In my local testing, these two lines caused crashes. The first one because it went over the 16 entries the vector had, and the second because it == .end(). This aren't proper fixes, but at least you'll be able to load a couple more BMS files without stepmania telling you to go to hell.
> Couple hack-fixes for BMS crashes.

- .travis.yml
Hopefully will fix Travis for us.  I'm not sure how to test this on my own.
Recommended by Travis docs: http://docs.travis-ci.com/user/installing-dependencies/
We may eventually want to look into whether the before_install/install hooks are supposed to be used for this rather than before_script.  The documentation examples aren't entirely clear themselves (and it doesn't look like there is much distinction between steps besides the order they come in).
> Travis: add apt-get update and -y to dependency installation

- src/MusicWheel.cpp
- src/WheelBase.cpp
Currently if a theme enables OnlyShowActiveSection for its MusicWheel, closing the active group (e.g. using Lua or the CloseCurrentFolder code) will result in an empty wheel.  This patchset fixes this so that when the active group is closed, all of the group titles are shown, and they are hidden again when a new group is selected.
The existing code was throwing out group titles when the cache for the Group sort order was being built, preventing us from ever displaying them in that sort, so the patches move that logic into SetOpenSection where we already have filtering code based on the active group.
This introduced an odd behavior where selecting a group could actually end ScreenSelectMusic and hang the program, which is where the fix in WheelBase comes in.  Thanks to whoever left that …
> Fix CloseCurrentFolder with OnlyShowActiveSection

- Themes/_fallback/metrics.ini
- src/MusicWheel.cpp
- src/MusicWheel.h
IIDX hides inactive sections, but unlike the current behavior of our
OnlyShowActiveSection metric (based on certain Pumps according to
DaisukeMaster's comment), it retains the section title so that the
section can be closed normally.
New metric: MusicWheel.HideActiveSectionTitle, defaulting to true in
_fallback.  A bit unfortunate, but keeps backward compatibility with the
existing behavior of OnlyShowActiveSection.
If neither metric is true, wheel displays all titles plus the contents
of the active section (if any).
If OSAS is true but HAST is false, wheel displays the active section
title plus its contents, or all titles if no section is active.
If both are true, wheel displays only the active section's contents, or
all titles if no section is active.
> Allow OnlyShowActiveSection wheel to include current section title

- Docs/Changelog_sm5.txt
- Docs/Luadoc/Lua.xml
- Docs/Luadoc/LuaDocumentation.xml
- src/Actor.cpp
- src/Actor.h
- src/ActorFrame.cpp
Added actor wrapping mostly so I can do this:
SCREENMAN:GetTopScreen():xy(-_screen.cx, -_screen.cy):AddWrapperState():xy(_screen.cx, _screen.cy):spin():effectmagnitude(0, 0, 1)
This makes Actor::Draw kinda duplicate a lot of the behavior of ActorFrame's draw functions, because it simulates descending a list of nested ActorFrames, so any future changes to ActorFrame::DrawPrimitives should be checked to make sure wrapper states produce the same behavior.
> Added wrapper states to actors.

- configure.ac
- src/Makefile.am
- src/RageUtil.cpp
As @shakesoda +1'd.
Steps to use:
1. Pull this branch
2. Run `./autogen.sh` and `./configure --with-system-pcre`. `make` should build successfully.
> Allow building against system PCRE library

- Xcode/scripts/mkrelease.rb
ProductInfo.h used to contain both Family and Version information.  This is no longer the case.
Family (StepMania) is now grabbed out of ProductInfo.h, and
Version (5.0.x) is now grabbed out of ver.h
> fix OS X bundle scripts

- Manual/index.html
The link to compiling stepmania in the manual index went to a dead google page. Replaced it with a link to compiling stepmania in the wiki.
> changed dead link in manual

- src/Song.cpp
Testing this on my machine, with 15k songs, startup time went from ~700 seconds to ~300 seconds.  So this probably cuts startup time in half.  All it does is use the music length that was already being stored in the cache instead of hitting the disk to read the music file every time.
> Use cached song length.

- src/Difficulty.cpp
- src/GameConstantsAndTypes.cpp
- src/IniFile.cpp
- src/IniFile.h
- src/NotesLoaderSM.cpp
- src/NotesLoaderSM.h
- src/NotesLoaderSSC.cpp
- src/PrefsManager.cpp
- src/RageTimer.h
They were using huge else if chains instead of a map.  Everybody knows else if chains on string comparisons are slow, so I went through and converted them to use maps of function pointers.
Some data on how much this improved startup time for me:
Hardware:  AMD Sempron 4 core from mid-2011.  Can't remember my HD specs, but I know it's a 1.5TB non-SSD from mid-2011.
Testing method:  Used my spare computer which has nothing else running on it.  Prior to each run of stepmania, I ran shutdown -r to eliminate effects of non-Stepmania levels of cache (OS or HD caching filesystem accesses).
3 measurements were taken at each of three builds:  SM5b4 (roughly, what was master in late October 2014), use_cached_length (current master with the PR #492 merged), and improved_notes_loader (PR #492 plus …
> Improved NotesLoaderSSC and NotesLoaderSM

- Themes/_fallback/Languages/en.ini
- src/AutoKeysounds.cpp
- src/GameState.cpp
- src/GameState.h
- src/NotesLoaderSSC.cpp
- src/NotesWriterSSC.cpp
- src/ScreenEdit.cpp
- src/ScreenEdit.h
- src/ScreenSelectMusic.cpp
- src/Song.cpp
- src/Song.h
- src/SongUtil.cpp
- src/SongUtil.h
- src/Steps.cpp
- src/Steps.h
This adds a tag to the note data section of the ssc file that can be set to make that chart load a different music file.
GameState::ForceOtherPlayersToCompatibleSteps() is called whenever ScreenSelectMusic changes the steps for a player to ensure that all players are on steps that use the same music file.  That function also checks the styletype, so it should resolve the disagreeing steps problem in #30 by not allowing the steps to ever disagree.  So if per-chart music is rejected by other devs, I'll put GameState::ForceOtherPlayersToCompatibleSteps() in its own pull request.
> Per-chart music files.

- src/Difficulty.cpp
- src/GameConstantsAndTypes.cpp
- src/IniFile.cpp
- src/IniFile.h
- src/NotesLoaderSM.cpp
- src/NotesLoaderSM.h
- src/NotesLoaderSSC.cpp
- src/PrefsManager.cpp
- src/RageTimer.h
- src/XmlFile.cpp
- src/XmlFile.h
- src/XmlFileUtil.cpp
A proper rebasing this time.
This covers a number of changes to existing loading code to load things more efficiently.
So far, it rewrites NotesLoaderSM, NotesLoaderSSC, and IniFile::ReadFile to not use else if chains, as well as a couple string converts that used long else if chains.
It also changes XNode to use a multimap for looking up children by name.
The changes to IniFile and XNode matter a lot for reading the banner cache index file, which used to be 51 seconds (with debugging symbols), and is now 0.13 seconds (with debugging symbols) for me. That was the source of the big hang before it started loading songs.
Because this changes critical parts of loading, it should have a test build for wider testing before being released.
Next target is going to be GameState::Reset.
> Load opt 2

- src/arch/ArchHooks/ArchHooks_MacOSX.cpp
As of commit dd0896d3eb89dfec7fca77fe6688400fd31078b6, a "StepMania 5" directory is searched for at ~/Desktop and created if one is not found.  It doesn't seem that directory is ever used in any way, however, causing confusion and annoyance for OS X users.
See: http://www.stepmania.com/forums/general-questions/show/1893
> prevent OS X Desktop directory from being created

- Docs/Themerdocs/Examples/Example_Actors/ActorFrameTexture.lua
Added a note to example 3 specifying that it was demonstrating the "float" property.
Added information about functionality I only just realized existed: the ability to draw outside of the screen's draw cycle.
> Update AFT examples

- src/ActorFrameTexture.cpp
Attempting to create a texture of 0 size or a texture with a name that
is already in use would crash SM.
> Prevent 2 AFT related crashes

- src/Background.cpp
- src/Player.cpp
- src/ScreenGameplay.cpp
- src/ScreenSyncOverlay.cpp
- src/SongPosition.cpp
- src/TimingData.cpp
- src/TimingData.h
GetBeatAndBPSFromElapsedTime and GetElapsedTimeFromBeat were walking through the entire list of timing segments every time.  This was a measurable problem on songs with a large number of stops or other segments.  This should mitigate that somewhat by making sure that they never have to traverse more than 32 segments to find the value.
> Faster TimingData lookups

- src/CMakeData-arch.cmake
- src/arch/ArchHooks/ArchHooks_MacOSX.mm
This replaces pull request #507; it also includes a commit which updates *CMakeData-arch.cmake* to use the new .mm file.  I've tested it with the included Xcode project file, and by generating a new Xcode project file using CMake.  Both build without issue.
> OS X Version Log Fix -- v2

- src/arch/InputHandler/InputHandler_MacOSX_HID.cpp
This should fix #504.
This is slightly different than the patch that serynth verified in that thread. I modified it so that it will still log an error message when translation fails. I excpect this minor change should compile and work just fine, but I was unable to test that as I lack access to a Mac.
> Fix OSX key translation crash (#504)

- src/CMakeLists.txt
A new target is introduced called `dmg`. This must be run explicitly.
Upon running it, it creates the dmg file.
The target respects if we are in a full release or not.
This will officially deprecate the ruby release script in the Xcode
folder upon a successful merge.
> Allow generating dmg files thanks to cmake.

- Themes/_fallback/metrics.ini
This fixes some of the inconsistent menu behavior observed in #525. 
Everything is still correctly reloaded in the same way as before when the game mode is changed, but when the mode isn't changed, the 'exit' button behaves the same as the exit button in every other menu by returning the user to parent options menu.
> 'Exit' option in 'select game' menu returns user to main options menu unless the game mode was changed

- src/NoteData.cpp
When clearing a range, if the first note in any track in the range was a
hold note, it would place it a hold the end of the cleared range.
> ancient NoteData::ClearRangeForTrack bug fix

- Build/INSTALL.md
- Build/license_install.txt
- CMake/CPackSetup.cmake
- CMake/DefineOptions.cmake
- CMake/Modules/FindVa.cmake
- CMakeLists.txt
- extern/CMakeProject-tomcrypt.cmake
- src/CMakeLists.txt
There are two targets you may not be familiar with, `install` and `package`.
* For Linux, `install` now defaults to `/usr/local`, but you can set it back to `/opt` with `cmake -DCMAKE_INSTALL_PREFIX=/opt` if you wish.
* For Windows, `install` may not work, but this is not a target you would want usually.
* For Linux, `package` has not been tested yet. It will likely create an archive file of what is installed.
* For Windows, `package` will create an NSIS package that can be used to install StepMania. One minor change as a result is that the binary and companion dlls will be placed in `bin` instead of `Program` now, but it makes no difference code-wise.
Mac OS X users: for now, use the `dmg` target instead.
This commit does *not* deprecate the original nsi script yet. The Texture Font …
> Provide initial cpack support. Mainly for devs.

- Themes/_fallback/Scripts/01 IniFile.lua
- Themes/_fallback/Scripts/02 ThemePrefs.lua
- Themes/_fallback/Scripts/02 ThemePrefsRows.lua
- Themes/default/BGAnimations/ScreenOptionsService in.lua
- Themes/default/BGAnimations/ScreenTitleMenu decorations.lua
This is a set of four commits that fix a variety of issues in _fallback's ThemePrefs system and default's use of it.  Refer to each individual commit message for more information.
I've tested every scenario I can think of, but it is *very* possible I've missed some edge case(s) or even some common usage I just haven't thought of.  With that in mind, I think it's worth having someone test this and experiment with it prior to merging.
> Fix theme prefs

- src/GameManager.cpp
- src/NotesLoaderBMS.cpp
* default key configuration slightly tweaked
* NotesLoaderBMS now reads "expert" substring in a bms title and assigns it expert difficulty
* play modes beat-versus5 and beat-versus7 now use single5 and single7 steps type respectively, beat versus mode now works as expected
* no revert commits :^)
> Beat mode gameplay changes, third attempt

- src/NoteDataUtil.cpp
* backwards modifier works like beatmania's mirror mod
* shuffle modifier works like beatmania's random mod, and produces same shuffle for both players
* both modifiers only affect keys, preserving turntable notes
> Backwards and shuffle mods now ignore turntable in beat-single5/7

- src/StepMania.cpp
Previously, inputting the code for BackInEventMode would only work if player 1 was active. Now the code works for both players.
> BackInEventMode code now works for both players (new version)

- CMake/Modules/FindJACK.cmake
Some missing lines in FindJACK.cmake resulted in cmake not finding jack. Missing lines added and JACK is now found as expected.
> Added missing lines of FindJACK.cmake - now finds JACK successfully

- src/NotesLoaderBMS.cpp
Previously, any Lua-based background animations called from BMS files would have the "StretchNoLoop" effect put on them, making them work incorrectly. Lua animations now use the "Centered" effect and appear as expected, while all other BG animations (avi, mp4, etc) use the standard "StretchNoLoop".
> Lua BGAnimations now work correctly when called from BMS files.

- src/NotesLoaderBMS.cpp
#difficulty tag in BMS files now works as expected (#difficulty 1 = beginner, #difficulty 4 = hard, etc.).
> BMS loader now supports #difficulty tag.

- Themes/_fallback/metrics.ini
- src/ScreenSelectMusic.cpp
- src/ScreenSelectMusic.h
Music wheel preview fadeout time is now adjustable, allowing for perfect loops if desired. Fallback theme metric added accordingly, corresponding to original hardcoded value.
> Music wheel preview fadeout time is now adjustable by the metric [ScreenSelectMusic] SampleMusicFadeOutSeconds.

- src/arch/LoadingWindow/LoadingWindow_MacOSX.h
- src/arch/LoadingWindow/LoadingWindow_MacOSX.mm
This commit allows OS X users to enjoy their current theme's custom splash graphic if it is available at ```./Graphics/Common splash.png```  I have been wanting to fix this for a fairly long time.
My fix is probably not the cleanest or proper way to do this.  StepMania.cpp [already looks up the current theme's "Common splash.png"](https://github.com/stepmania/stepmania/blob/master/src/StepMania.cpp#L1119-L1126) and passes it off to the arch-appropriate LoadingWindow as a RageSurface.  This fix ignores that Ragesurface, repeats the lookup in LoadingWindow_MacOSX.mm, and loads the splash image into a Ragefile which is easily loaded into an NSImage.
Still, my fix does work, and if you actually know how to work with a Ragesurface and can help out here, I'll give you a cookie. :)
> fix LoadingWindow splash image for OS X

- src/NotesLoaderBMS.cpp
- src/Song.cpp
For songs with a preview file, setting the sample length to 0 now causes Stepmania to automatically set the sample length to the length of the whole preview file. For BMS files, this is done automatically.
> Setting sample length for songs with preview file to 0 uses length of preview file

- src/arch/Sound/RageSoundDriver_AU.cpp
Replaced AudioDeviceGetProperty to AudioObjectGetPropertyData thus no longer using deprecated functions as specified here: https://developer.apple.com/library/mac/technotes/tn2223/_index.html
Additionally, I used https://reviewboard.asterisk.org/r/1040/diff/2/ for further assistance on how to set up the AudioObjectPropertyAddress object.
I tested this and did not seem to run into any issues regarding audio.
> Replaced Deprecated AudioDevice Functions

- src/AutoKeysounds.cpp
Previously in songs with keysounds when playing with two players, the manual keysounds would be panned to the player's respective side whereas autokeysounds would play panned center for both sides, resulting in them playing twice as loud and overpowering everything else.
Keysounds now work correctly in 2 player mode, where player 1's key presses come through the left speaker, player 2's key presses come through the right speaker, and any automatically played keysounds are played through both speakers at the correct volume.
> Autokeysounds are no longer twice as loud when playing keysounded charts with two players.

- .gitmodules
- Build/README.md
- README.md
- extern/CMakeLists.txt
- extern/CMakeProject-cppformat.cmake
- src/CMakeLists.txt
This is the cppformat library to be used with std::string calls.
This will be part of a bigger project to utilize std::string instead of StdString::CStdString, aka RString.
Remember to read the updated documentation: usage of `git submodule init` and `git submodule update` are required.
> Prove that submodules can work.

- src/NoteDisplay.cpp
hi.
This PR is fix hold bottom cap drawing bug.
bug sample1---Stopped scroll bottom cap
(noteskin:ya_solo_hd http://waiei.net/wiki/sm5_ya_solo_hd.html)
commit 771e24d
https://youtu.be/MVC_wNsWvn8
This PR
https://youtu.be/SsN-GmRsLAs
sample2---1px gap (noteskin:exactv2)
I'm expecting a new note of drawing 5.1.
This PR is I want you to adopt as first aid until that time.
thanks!
> Fix 2D noteskin's hold bottom cap drawing bug

- src/StdString.h
Remove a fair amount of logic working around a bug in VC5 that caused
the heap to be corrupted when assigning a shorter string to
an existing, larger string (KB 172398).
> Remove old VC5/6/7 cruft

- .gitignore
- StepmaniaCore.cmake
- src/CMakeLists.txt
Now Linux can join in on different binary names.
> Use the more appropriate output name properties.

- src/Background.cpp
3.9 would make lead-in images appear no matter what, and still maintained the proper sync demanded by having a negative beat. This PR just restores the behavior to what 3.9 did, since currently negative BGAnimation beats will disable lead-in images.
> Have lead-in image appear even with a negative BGAnimation beat

- Build/README.md
I thought that Build/README.md need to describe about cmake install by each platform because my environment didn't install cmake. So, in this request, I described how to install cmake on Mac OS X because my platform is Mac OS X. Then, I think it needs to describe Windows and Linux.
> Add information: Build/README.md.

- Themes/_fallback/Languages/ja.ini
I fixed mistranslation of explanation LIFE DIFFICULTY in Advanced Options Japanese version.
The English sentence is "Increase this value to cause your life meter to drain faster and refill slower".
When some user changes to increase LIFE DIFFICULTY for easier to expect clear the game, they will confuse.
> Fix mistranslation in one line:  Themes/_fallback/Languages/ja.ini

- src/NoteDisplay.cpp
This pull request fixes drawing hold bottomcap when NoteDisplay is zoomed out.
(ex. techno-versus8 and techno-double8)
> Fix hold bottomcap when NoteDisplay is zoomed out.

- src/arch/Lights/LightsDriver_Linux_PIUIO_Leds.cpp
- src/arch/Lights/LightsDriver_Linux_PIUIO_Leds.h
Previously, the code here logged every LightState of every PIUIO_Led light with every call of `Set()`.
This commit adds checks to see if each of the PIUIO_Leds have changed LightState since the last `Set()` and skips logging the current LightState if there is no change.  Each set of lights was already being looped through; the new code here just issues a continue to skip logging where possible.
This helps reduce CPU usage when PIUIO_Leds are in use as the LightsDriver.
I've done some informal verification by eyeballing the output of htop:
Before - *udev* using ~10.0% CPU
---
After - *udev* using ~0.0% CPU
---
Still, this sort stuff is admittedly outside my expertise, so any comments/criticisms are welcome!
> reduce udev logging of PIUIO LightState changes

- Themes/_fallback/metrics.ini
Setting the variable to true maintains behavior consistent with stable releases.
> Change RandomBGEndsAtLastBeat metric to true by default

- src/NotesLoaderBMS.cpp
This pull requests extends BMS loading in the following ways:
* Add support for setting a preview point when using the #MUSIC tag.
* Add support for myo2 chart layout.
* Add support for a linear solo layout. (Channels 11, 12, 13, 14, 15, 17)
* Add support for kb7 layout charts.
* Fix offset not being applied (Since it was being reset)
> Additional BMS layouts for different styles.

- src/RageFileManager.cpp
By default on linux, stepmania installs to `/usr/local/stepmania-5.0/stepmania`. Since this is not on the default path, I find myself creating a symbolic link from `/usr/local/bin/stepmania -> /usr/local/stepmania-5.0/stepmania` (or similar). However, this causes stepmania to think it is running from `/usr/local/bin` instead of its actual install directory, and so it fails to find the Songs and Themes directories, etc.
This PR fixes things such that Stepmania finds the full path of the directory containing the *actual* binary, and not some symbolic link to it.
I tested it very thoroughly on Linux - launching stepmania by absolute path to binary, relative path, relative path to a symlink pointing to the absolute binary path, relative path to a symlink pointing to the relative binary path, …
> Follow symbolic links when searching for executable directory

- src/RageUtil.cpp
`power_of_two` using math functions is not only inefficient, but also causes Intel C/C++ Compiler linking it to Intel's math library `libmmd` (which can not be statically linked).
This commit rewrites `power_of_two` to get rid of math functions, making use of a simple binary search. It is much faster than math version (even faster than initial while-loop version, I did a full execution time test).
> Rewrite power_of_two, using binary search.

- CMake/DefineOptions.cmake
- StepmaniaCore.cmake
- src/CMakeLists.txt
- src/RageSoundReader_FileReader.cpp
- src/config.in.hpp
* All OSes can now take advantage of it.
* Mad is not linked if not utilized.
* Mac OS X side has a cleaner library list setup now.
> Improve and enhance WITH_MP3.

- CMake/DefineOptions.cmake
- StepmaniaCore.cmake
- src/RageSoundReader_FileReader.cpp
- src/config.in.hpp
As before, set WITH_WAV and WITH_OGG to off to limit your playing experience. Why this would be done is beyond me, but it's available.
> Allow changing WAV and OGG settings for all OSes.

- NoteSkins/pump/default/NoteSkin.lua
Unless this is a compatibility code for something/there is a inexplicable bug somewhere that needs this here.
> Removed redundant code at Noteskins/pump/default/Noteskin.lua

- StepmaniaCore.cmake
- src/RageFileManager_ReadAhead.cpp
- src/config.in.hpp
It is unclear why this was removed.
If this needs to be removed again, either do so through the config file or the definition checks.
> Re-implement the check for HAVE_POSIX_FADVISE.

- src/CMakeLists.txt
The speed is brought back up to reasonable limits considering I work with a VM primarily.
> Re-enable precompiled headers for Windows.

- extern/CMakeProject-lua.cmake
`lua.c` is needed for Lua interpreter, not in Lua library (see [these lines] (https://github.com/stepmania/stepmania/blob/master/extern/lua-5.1/INSTALL#L74-L82)), thus removing it.
> Remove lua.c from CMake project.

- CMake/Modules/FindIconv.cmake
- StepmaniaCore.cmake
- src/CMakeLists.txt
This removes the need for the arbitrary other linker flags.
This is required to allow for proper building of ffmpeg (the next goal).
> Reference bzip2 and iconv on Mac OS X properly.

- Docs/Luadoc/LuaDocumentation.xml
- src/Sprite.cpp
- src/Sprite.h
And do what their names say.
This completely changes the behavior of both functions, read the comments added to Sprite.cpp for details.
Polling theme authors by asking only turned up 1 out of 6 that used either, but using grep on themes turned up substantially more (including one author that said they weren't using scaletoclipped).  So the change will affect existing themes, unless the places they used it were just bugs they hadn't found yet.  It won't cause lua errors, but will cause visual differences.
> Rewrote Sprite::ScaleToClipped and CropTo to actually work.

- CMake/Modules/FindFFMPEG.cmake
When turning the WITH_SYSTEM_FFMEG option on, the CMake configuration incorrectly adds ffmpeg subdirectories (like `/usr/include/libavutil`) to the compiler's `-I` flag. This can cause files containing `#include <time.h>` to include `libavutil/time.h` instead of the original intended file, which breaks compilation on Linux.
This pull request fixes this bug.
Note that #331 is not included here, since it still breaks compilation on Windows.
> Fix CMake build with option WITH_SYSTEM_FFMPEG

- .travis.yml
- CMake/SetupFfmpeg.cmake
- StepmaniaCore.cmake
- extern/CMakeProject-cppformat.cmake
- extern/CMakeProject-googletest.cmake
- extern/CMakeProject-tomcrypt.cmake
- extern/CMakeProject-tommath.cmake
- src/CMakeLists.txt
Eventually, there will be options to disable building the unit test portions explicitly. That will come later.
> Enforce submodule and compiler safety with builds.

- src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
- src/arch/MovieTexture/MovieTexture_FFMpeg.h
Fixes crashes with recent version of libav and ffmpeg on Linux while attempting to play a video
> FFMpeg: Fix uninitialized AVFrame

- src/TimingData.cpp
The global offset is a correction for audio latency, which is measured
in wall-clock time, but TimingData elapsed time values represent offsets
into the sound file.  To get the offset in the sound file that
corresponds to the wall-clock time of the global offset, we have to
multiply by the music rate.
> Fix interaction between global offset and music rate.

- Docs/Luadoc/LuaDocumentation.xml
- src/Sprite.cpp
- src/Sprite.h
ScaleToClipped needs to use custom tex coords to prevent the scale effect from tweening on.
Reverts stepmania/stepmania#203
> Revert "Rewrote Sprite::ScaleToClipped and CropTo to actually work."

- CMake/Modules/FindDirectX.cmake
Every DirectX SDK installation brings in an environment variable `DXSDK_DIR`, pointing to the directory where Direct SDK is installed. We can set search paths cleanly by reading this environment variable.
If this variable does not exist, we can tell that there is no DirectX SDK.
> Read DirectX SDK path from environment variable.

- src/PlayerOptions.cpp
When disqualification was turned on via Preferences, the old logic exhibited two problems:
1. charts with attacks were always disqualified from ranking
2. charts without attacks could be disqualified from ranking if the attack modifier was set to "Off"
So, this commit fixes those problems.  If a chart has attacks, and the attack modifier is used to turn them "Off", then disqualification is enforced.
Additionally, disqualification is enforced if the attack modifier is set to "Random Attacks."  This part might not be necessary, but I acted on the assumption that random attacks could theoretically make a chart easier.
> fix logic for attacks in gameplay disqualifying

- src/LifeMeterBar.cpp
- src/PrefsManager.cpp
- src/PrefsManager.h
This preference existed in previous versions of StepMania (3.95, at least) and is needed to properly emulate certain games (namely, In The Groove).
This PR brings back the code as seen here: https://github.com/sigatrev/Stepmania-3.95/blob/4af304c51aeeedacd07f612d7f0e5ecaa81cce19/LifeMeterBar.cpp#L228-L233
Unlike in SM3.95, however, I've now set the default value to be 5, the same as the `RegenComboAfterMiss`.  If players don't change the value, they won't see any difference in behavior in SM5.
If players want, they can manually set the preference to 10 (or a value of their choosing) to emulate the game of their choice.
> reinstate MaxRegenComboAfterMiss Preference

- src/RageBitmapTexture.cpp
- src/RageFileManager.cpp
- src/RageSoundPosMap.cpp
- src/ScreenEvaluation.cpp
- src/TimingData.cpp
- src/arch/Lights/LightsDriver_Linux_PIUIO.cpp
This commit attempts to eliminate GCC 5 warnings on Linux (as tested by Travis CI), leaving an only warning to be resolved:
```
/home/travis/build/Prcuvu/stepmania/src/archutils/Unix/BacktraceNames.cpp:455:2: warning: #warning Undefined BACKTRACE_LOOKUP_METHOD_* [-Wcpp]
#warning Undefined BACKTRACE_LOOKUP_METHOD_*
^
```
Which macro should we actually use to kill this warning?
> Fix GCC warnings on Linux.

- src/global.cpp
- src/global.h
This one is relatively safe to modify: all calls are handled through defined macros.
The macros themselves will be looked at another day.
This commit may potentially be cherry-picked into master with no issues.
> Have sm_crash use std::string now.

- src/Font.cpp
- src/LuaBinding.cpp
- src/LuaBinding.h
- src/LuaManager.cpp
- src/LuaManager.h
- src/RageLog.cpp
- src/RageSoundReader_Vorbisfile.cpp
- src/RageThreads.cpp
- src/RageThreads.h
- src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
- src/global.h
Also, investigated the `%p` issue. Explicit casts to `(void *)` can still work. Unsure if it's a good idea all the time, but one step at a time perhaps.
The only usages of `vssprintf` now are tied to our custom `ssprintf` function. I do not trust that just replacing the functionality with `cppformat` will work here. That is for later tonight I guess.
> Use more of std::string and fmt::sprintf.

- src/RageUtil.cpp
- src/rage/RageString.cpp
- src/rage/RageString.hpp
- src/tests/RageStringTest.cpp
This is being done to prepare for valid `cppformat` combinations.
> Use an alternative hex calculation for wchar_t.

- src/NotesWriterSSC.cpp
This is a prep commit for eventual removal of vsnprintf. Not much left uses it.
> Use std::string for writing.

- src/FontManager.cpp
- src/Profile.cpp
- src/RageFileBasic.cpp
- src/RageFileDriverZip.cpp
- src/RageSound.cpp
- src/RageSurface_Load_PNG.cpp
- src/RageUtil_BackgroundLoader.cpp
- src/SongManager.cpp
- src/arch/InputHandler/InputHandler_MacOSX_HID.cpp
- src/arch/Sound/RageSoundDriver_Generic_Software.cpp
- src/archutils/Darwin/HIDDevice.h
- src/archutils/Darwin/KeyboardDevice.cpp
- src/archutils/Win32/GraphicsWindow.cpp
- src/archutils/Win32/RegistryAccess.cpp
- src/archutils/Win32/USB.cpp
This will help with `fmt::sprintf` and `fmt::format`.
> All %p calls should be casted now.

- src/archutils/Win32/GraphicsWindow.cpp
- src/global.h
Note to self: ensure ALL `CHECKPOINT;` calls go away.
> Fix Windows specific issues.

- src/NotesLoaderBMS.cpp
As before, merely checking that a chart has 7 keys non-empty does not mean it's an actual kb7 file, as it may have a gap for whatever reason.
This PR adds checks on whether it uses all 7 channels on the only valid kb7 bms layouts before actually stating "Yes, this is a kb7 file", giving beat-single7 priority if not.
> Make sure kb7 is the appropiate steps type.

- src/CMakeData-arch.cmake
This is meant to enhance #343.
> Allow all OSes to use the Sextet light drivers.

- src/CMakeLists.txt
antes de compilar con make, es necesario identificar:
ubuntu:: x32 (32bit) -> i686
gracias
> i686 -> x64 recognition before make

- README.md
With `WITH_STATIC_LINKING` turned on, additional redistributable packages should not be needed.
Players report "Missing `d3dx9_43.dll`" errors because they haven't installed [DirectX End-User Runtimes (June 2010)](http://www.microsoft.com/en-us/download/details.aspx?id=8109). Worth mentioning in `README.md`.
> [Windows] Update README.md.

- .appveyor.yml
- Build/README.md
With no NT6-specific functions implemented, Windows XP can still be supported.
Hopefully 5.0.10 and 5.1.0 Alpha installers can be updated to support Windows XP.
> [Windows] Build using platform toolset "v140_xp" on AppVeyor.

- src/AdjustSync.cpp
- src/AdjustSync.h
- src/CMakeProject-rage.cmake
- src/ModValue.h
- src/NoteDisplay.cpp
- src/config.in.hpp
- src/rage/RageConfig.hpp
- src/rage/RageMath.hpp
- src/tests/RageMathTest.cpp
Once SM6 hits, no more VS2013. Consider yourselves warned.
> Restore VS2013 compilation.

- src/Game.cpp
- src/GameConstantsAndTypes.h
- src/GameState.cpp
- src/NoteDataUtil.cpp
- src/NoteDataUtil.h
- src/NoteDisplay.cpp
- src/NoteTypes.h
- src/Player.cpp
- src/Player.h
- src/PlayerState.cpp
- src/PlayerState.h
- src/ScreenEdit.cpp
- src/ScreenGameplay.cpp
There was a bunch of code for handling guitar-specific input such as hammer-ons/pull-offs and strumming. Given that guitar was removed, and as far as I understand, will not be added back into SM5, it makes sense to remove code that had no other use.
I have tested this, everything seems to work fine.
> remove guitar cruft

- src/GameManager.cpp
It made some sort of sense to only have three judgment levels before, but it makes far more sense to let the theme manage it now, instead of being hard coded into the engine, since it isn't necessarily the case anymore.
> Unrestrict pop'n judgment levels

- src/LuaManager.cpp
Also reduce redundancy while we're at it.
> Prevent crashes if lua_tostring is nullptr.

- src/RageSurface_Save_PNG.cpp
- src/Texture Font Generator/Utils.cpp
Using the correct "destroy" function for the `png_struct` in `SavePNG` (`png_destroy_write_struct` as opposed to `png_destroy_read_struct`) seems to prevent the crash described in #964 . Removing the "filler" transformation function specification (`png_set_filler`) in Texture Font Generator's `SavePNG` allows the PNG creation to succeed (no filler transformation is necessary when we're writing an RGBA image to a PNG with alpha channel).
> Fix Texture Font Generator PNG write

- src/RageFileManager.cpp
This should fix problems that occur when moving simfiles from an OS X machine to another platform, which tends to create files that start with "._".  This can cause songs to not load.
I don't have any simfiles from an OS X machine to test with, so someone else needs to check this.
> Ignore OS X special files

- Docs/Luadoc/Lua.xml
- Docs/Luadoc/LuaDocumentation.xml
- Themes/default/BGAnimations/ScreenEvaluation overlay/default.lua
- Themes/default/BGAnimations/ScreenGameplay overlay.lua
- Themes/default/Graphics/pause_menu.lua
- Themes/default/Languages/en.ini
- Themes/default/Scripts/04 Other.lua
- Themes/default/metrics.ini
- src/Screen.cpp
- src/Screen.h
- src/ScreenGameplay.cpp
- src/ScreenGameplay.h
- src/ScreenSelectMusic.cpp
Pause menu activated by pressing one of the pause buttons (start, select, or back) twice in less than half a second without pressing anything else.  Hopefully pad players with Start mapped to a corner won't trigger it on accident.
> Pause menu for default theme.

- src/Model.cpp
- src/rage/RageMath.hpp
This fixes bones and animations for models with per-mesh bones.
> Apply inverse bind pose matrix for per-mesh bones

- CMake/SetupFfmpeg.cmake
When the CMake flag is specified for position independent code, FFMPEG will be compiled with the `--enable-pic` flag.
This fixes a broken build on recent Fedoras and other platforms desiring hardened builds.
> Compile FFMPEG in PIC when configured as such.

- extern/CMakeProject-glew.cmake
- extern/CMakeProject-json.cmake
- extern/CMakeProject-lua.cmake
- extern/CMakeProject-mad.cmake
- extern/CMakeProject-ogg.cmake
- extern/CMakeProject-png.cmake
- extern/CMakeProject-tomcrypt.cmake
- extern/CMakeProject-tommath.cmake
On Linux when building this under RPM, RPM insists on linking in standard system libraries like libpng, libjpeg-turbo, libGLEW, Lua, etc. because we are removing the RPATH from the binary for security reasons. This patch causes all dependencies to be statically compiled into the binary, which is ideal as the alternative is segfaulting because of incompatible library changes.
StepMania also uses a modified Lua library which exports functions that don't exist in any standard Lua library, so there's no easy way around this.
The only other solution appears to be to rewrite StepMania source code to update it to use modern libraries, but that doesn't seem likely to happen and would involve a lot of effort.
This solves #1008.
> Compile dependencies statically into the binary.

- src/Course.cpp
- src/Course.h
- src/StepsUtil.cpp
- src/StepsUtil.h
Unfortunately, I'm unable to apply the same fix that applies to Endless to Oni or Extended, as those two works much differently. 
Extended probably works the same way as Endless, though, but Oni is a different beast.
Reference: #1020
> Fixes #1020 and add songs that are missing a Medium difficulty to the Endless Course.

- src/RageInputDevice.cpp
Add missing ':' (colon) key binding as stated in Keymaps_ini_format.md in the user doc.
> Add missing ':' key binding

- src/NoteData.cpp
- src/NoteData.h
- src/NotesLoaderBMS.cpp
When checking for the first second in a song, AutoKeysound notes are now ignored, being treated as if they were background music. This allows the intro of BMS files to play as soon as ScreenGameplay is loaded, while still having a delay before the real notes come in.
> Checking for first second now ignores autokeysounds

- Docs/Luadoc/Lua.xml
- Docs/Luadoc/LuaDocumentation.xml
- src/Profile.cpp
- src/Profile.h
- src/ProfileManager.cpp
- src/ProfileManager.h
For managing scores that need to be separated.
Considering rewriting what score data is saved to allow converting a score between systems after the fact.
> Add stats prefix feature to ProfileManager

- src/ActorMultiVertex.cpp
- src/NoteDataUtil.cpp
- src/NoteDataWithScoring.cpp
- src/NoteDisplay.cpp
- src/NoteSkinManager.cpp
- src/NotesLoaderBMS.cpp
- src/NotesLoaderSSC.cpp
- src/NotesWriterDWI.cpp
- src/NotesWriterSM.cpp
- src/NotesWriterSSC.cpp
- src/PlayerOptions.cpp
- src/RageDisplay_OGL.cpp
- src/ScreenTextEntry.cpp
- src/ThemeManager.cpp
- src/TimingData.cpp
- src/XmlToLua.cpp
- src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
- src/archutils/Darwin/JoystickDevice.cpp
- src/archutils/Darwin/MouseDevice.cpp
* Ensure all switches have a default when working with enums.
* Match defined new[] calls with delete[] calls.
* Respect variable initialization order.
> Clean up three sets of warnings:

- Docs/Themerdocs/item_scroller.md
- Docs/Themerdocs/lua_config_system.md
This commit adds Lua syntax highlighting via GitHub Flavored Markdown under the notion that many novice themers will be viewing the .md files in a web-browser at GitHub.
> include syntax highlighting in ThemerDocs markdown

- src/Actor.h
- src/ArrowEffects.cpp
- src/Attack.h
- src/BeginnerHelper.cpp
- src/CreateZip.cpp
- src/CryptManager.cpp
- src/LuaManager.cpp
- src/ModelTypes.cpp
- src/MusicWheel.cpp
- src/ProfileManager.cpp
- src/RadarValues.h
- src/RageModelGeometry.cpp
- src/RageSoundReader_Resample_Good.cpp
- src/RageSurfaceUtils_Dither.cpp
- src/RageSurfaceUtils_Palettize.cpp
- src/RageSurface_Load_GIF.cpp
- src/RageThreads.cpp
- src/ScreenDimensions.h
- src/ScreenHowToPlay.cpp
- src/UnlockManager.h
- src/rage/RageConfig.hpp
Any float variables in non constexpr scenarios are left alone.
> Use constexpr where it is safe to.

- src/Sprite.cpp
- src/StreamDisplay.cpp
gcc 5.3.0 seams to need explicit namespace std:: for isnan
> [fix] add namespace to isnan

- src/LightsManager.cpp
Thank Trevor Barribeau for the fix.
This is required for the BlinkGameplayButtonLightsOnNote setting, particularly if it's set to 0 instead of 1.
> Don't reset lights due to settings.

- Themes/_fallback/Languages/en.ini
- src/Game.cpp
- src/GameInput.h
- src/InputMapper.cpp
- src/ScreenManager.cpp
- src/ScreenManager.h
- src/ScreenMapControllers.cpp
- src/StepMania.cpp
A few changes to allow mapping a key for taking screenshots, and using the Print Screen key for other things.
LightsDriver_SextetStream sets light states based on game buttons, so maybe adding a new game button affects lights somehow?
@psmay should look into this, since he did that lights driver.
> Remappable screenshot key

- src/ActorFrame.cpp
- src/NoteSkinManager.cpp
- src/Player.cpp
We were missing some LUA->Release calls.  It looks like this (particularly the edit in Player.cpp) will also magically fix memory card crashes on Linux.  It used to encounter a mutex "deadlock" on the first plug after playing a round, I assume due to the main thread getting a bunch of Luas without releasing, thereby preventing the memory card thread from ever getting any at all.
> Release Lua locks responsibly; fix a USB profile crash

- src/BGAnimationLayer.cpp
- src/RageUtil.cpp
- src/RageUtil.h
- src/ScreenMiniMenu.cpp
- src/TimingSegments.cpp
- src/XmlToLua.cpp
Replaces #1181.  This approach is different because adding a thousand try blocks to handle exceptions everywhere would be bad in its own way.
There might be a substantial performance hit from having a try block even when an exception is not thrown.  Somebody on Windows should compare how long stepmania takes to start up to see if this change slows down startup time.  StringToInt is used in several places in NotesLoaderSSC, so if this version performs worse, startup time will be slower with a large song collection.
> Use standard int/float conversion functions

- src/RageSoundReader_Resample_Good.cpp
- src/RageSoundReader_SpeedChange.cpp
- src/RageSoundReader_WAV.cpp
- src/RageSurface_Load_PNG.cpp
Pretty sure alloca inside a while loop was causing a stack overflow in the sound code.
alloca and setjmp/longjmp don't actually work together, so the png loading has also been changed to use exceptions instead of setjmp/longjmp, and new/delete instead of alloca.
> Alloca problems

- Docs/Themerdocs/5.1_incompatibilities/NewField_mod_system.md
- Themes/_fallback/Scripts/02 NewField.lua
- src/ModValue.cpp
- src/ModValue.h
- src/NewField.cpp
- src/NewField.h
- src/NoteData.cpp
- src/NoteTypes.h
- src/NotesLoaderSSC.cpp
This completely changes the syntax of the mod system in 5.1.
Inputs and operators are more cleanly separated.  There aren't weird warts on the input class like phase and repeat.  Those things are operators now.
The seed for the random input can be controlled now instead of being an awkward wart.
This breaks compatibility with any mod code written for the old 5.1 system.  Anything written for the previous system can be rewritten in the new system.
> 5.1 mod language rewrite

- src/Screen.cpp
copied the bit from ScreenTextEntry that turns a keyboard input into a
character to append so input callback functions can be used instead of
STE.
> add device character to input callback

- src/Player.cpp
- src/Player.h
- src/RageDisplay_D3D.cpp
- src/ScreenGameplay.cpp
Open to suggestions regarding the magic number I needed for my judgement optimization. Figured there was probably variables I could use to make it perfect, but couldn't find them. Using the magic number on-top of frame delta ensures none are missed, and no magic number didn't result in a performance gain despite not catching any missed arrows.
> Performance fixes + change song start delay based on music rate

- src/rage/RageVColor.cpp
This technique is outlined in http://stereopsis.com/sree/fpu2006.html, and is dirty but does seem to have a measurable effect on performance (especially in hold rendering). The game still works with this change and does not seem to have any major problems as a result.
> Use a trick to speed up RageVColor::ftoc

- CMake/DefineOptions.cmake
- CMake/Modules/FindSDL2.cmake
- StepmaniaCore.cmake
- Themes/_fallback/Languages/en.ini
- src/CMakeData-arch.cmake
- src/CMakeLists.txt
- src/RageDisplay_OGL.cpp
- src/arch/InputHandler/InputHandler_DirectInputHelper.cpp
- src/arch/LowLevelWindow/LowLevelWindow_SDL.cpp
- src/arch/LowLevelWindow/LowLevelWindow_SDL.h
- src/arch/arch_default.h
- src/archutils/Win32/GraphicsWindow.cpp
- src/archutils/Win32/GraphicsWindow.h
- src/config.in.hpp
- Creating SDL2 Windows for Linux and Windows and using OpenGL to render.
- Getting/Setting modes through SDL2
- Shutting down the game / Closing the Window by the X, ALT+F4 etc.
- Mac OSX port
- ~~After setting a mode, the new window will be located in the left upper corner of the display making it impossible to drag it.~~ (works now)
- D3D renderer will still use the "native" way.
> SDL2 windows

- Themes/_fallback/Scripts/02 lua_config_system.lua
- Themes/_fallback/metrics.ini
- src/GameState.cpp
- src/GameState.h
- src/MusicWheel.cpp
- src/PrefsManager.cpp
- src/PrefsManager.h
- src/Profile.cpp
- src/Profile.h
- src/ProfileManager.cpp
- src/RageUtil.cpp
- src/RageUtil.h
- src/ScreenSelectMusic.cpp
- src/Song.cpp
- src/Song.h
- src/SongManager.cpp
- src/SongManager.h
- src/Steps.cpp
- src/Steps.h
Profile::LoadSongsFromDir blocks without updating.
GameState::prepare_song_for_gameplay blocks without updating.
Sometimes scores on custom songs get removed when the song is played again.  _sometimes_
Scores that are in the player's profile seem to show up in the machine's high score list until the song is played.  No clue why.
CustomSongsEnable=0
CustomSongsLoadTimeout=5
CustomSongsMaxCount=1000
CustomSongsMaxMegabytes=5
CustomSongsMaxSeconds=120
NumProfileSongGroupColors=2
ProfileSongGroupColor1=PlayerColor(PLAYER_1)
ProfileSongGroupColor2=PlayerColor(PLAYER_2)
> Add support for custom songs from USB profiles.

- src/Actor.cpp
- src/Actor.h
This fixes a bug in the actor effect system that Kyzentun fixed in master branch, but not here.
Not backported from this commit is "Use correct draw time for hold heads" as that is related to the new notefield system.
> Backport commit cd5df01 from master branch

- src/NetworkSyncManager.cpp
- src/NetworkSyncManager.h
- src/NoteData.cpp
- src/NoteData.h
- src/ScoreKeeperNormal.cpp
- src/ScreenNetSelectBase.cpp
- src/ScreenNetSelectMusic.cpp
- src/Song.cpp
- src/Song.h
- src/Steps.cpp
- src/Steps.h
-- Send server the chart hash on song start (Can be used by the server to identify specific charts)
-- Send server the song's file hash on song select (To send to the other players in the room and so the server can identify what song was selected)
-- Send server the song's file hash on song start (So the server can identify the song, in case the user moved from the song he selected first to another one with the same metadata)
-- Recieve song's file hash when a song is selected
-- Find the song using the file hash(If no filehash was sent or the song isn't found using the filehash then search again without using the filehash)
-- Send the server the rate on song start
-- Added packet FLU(friendlist update). The friendlist is kept in 2 vector in the NSMAN called fl_UserNames and fl_UserStates …
> Online protocol improvements

- src/MessageManager.cpp
- src/StepMania.cpp
[I hit Enter too soon on the original submission... Edited.]
I did a release build (`-DCMAKE_BUILD_TYPE=Release`) of StepMania from the 5_0 branch using the latest g++ (6.3.1) on Fedora 25, and StepMania crashed on startup with the following stack trace:
```
#0  0x00000000006d4651 in MessageManager::Broadcast(Message&) const ()
#1  0x00000000006d48c2 in MessageManager::Broadcast(StdString::CStdStr<char> const&) const ()
#2  0x00000000006a37f3 in GameState::GameState() ()
#3  0x000000000068241a in sm_main(int, char**) ()
#4  0x00007ffff1bb6401 in __libc_start_main () at /lib64/libc.so.6
#5  0x00000000006795ca in _start ()
```
The relevant code:
```c++
void MessageManager::Broadcast( Message &msg ) const
{
// GAMESTATE is created before MESSAGEMAN, and has several BroadcastOnChangePtr …
```
> Cherry-pick "Instantiate MESSAGEMAN first" to fix a crash in release build

- src/Bookkeeper.cpp
- src/Bookkeeper.h
- src/GameCommand.cpp
- src/GameState.cpp
- src/SpecialFiles.cpp
- src/SpecialFiles.h
- src/StepMania.cpp
On Coins Insert a file Save/Coin.ini is created, if it does
not exist, which stores the number of coins currrently in
m_iCoins. Whenever m_iCoins is update, the Coin.ini is updated.
On boot, Coin.ini is read and m_iCoins is set to that value.
resolves: #1403
> Persistent Coins

- src/MusicWheelItem.cpp
This fixes a bug where player difficulty meter and/or color inside MusicWheelItem don't update when switching between difficulties.
> [MusicWheelItem] Call SetMessage during CurrentSteps/Difficulty Changed

- src/RageMath.cpp
This fixes the second argument of fmod to be a float, due to the original form not compiling under XCode (resulting in errors).
> Fix up RageTriangle's fmod usage.

- src/arch/InputHandler/InputHandler_DirectInput.cpp
- src/arch/InputHandler/InputHandler_DirectInput.h
- src/arch/InputHandler/InputHandler_DirectInputHelper.cpp
- src/arch/InputHandler/InputHandler_DirectInputHelper.h
The XBox360 controller driver for windows has a flaw where the DirectInput backwards-compatible driver registers dance pad arrows as a hat and will not allow opposite arrows to be pressed at the same time. This is not a problem in the XInput interface since the arrows are registered as a DPad and each arrow is a button.
This patch adds XInput support for the DirectInput driver. On initialization XInput controllers will be detected and registered first, followed by enumerating DirectInput devices. During DirectInput enumeration any XInput-capable controllers will be bypassed so that they aren't registered twice.
> XInput support for the DirectInput driver

- src/MusicWheelItem.cpp
On default theme on fresh checkout on fresh install of Arch, I
encountered a segfault when entering the ScreenSelectMusic screen. The
fault was trying to dereference a NULL pWID->m_pAction in the
WheelItemDataType_Sort case, which we fell through to because of the
missing break statements. This is a simple fix for that, which I believe to be the same issue as #1445
> Add missing breaks to case statement, fix #1445

- Themes/_fallback/Languages/en.ini
- src/ScreenDebugOverlay.cpp
Added to the Profiles page because that already has a line for writing preferences.
Entry in the debug menu that reloads preferences.  There may be some preferences that are only checked at startup that are unaffected by the reload.
> Reload Prefs debug menu entry

- Themes/_fallback/Scripts/02 ActorDef.lua
Without this, simfile lua has to fetch the current song dir and add the path to the graphics instead of being able to use a relative path.
Example of how a bg loaded from song_dir/animations/default.lua is affected by this fix:
Before this fix:
```lua
Def.Sprite{
Texture= GAMESTATE:GetCurrentSong():GetSongDir() .. "animations/foo.png",
}
```
After this fix:
```lua
Def.Sprite{
Texture= "foo.png",
}
```
> Fix relative paths in simfiles.

- src/archutils/Darwin/SMMain.mm
Before, going into full screen mode would give a black screen on Mac OS. You could get around it by clicking the green dot in the window bar, which uses Mac OS's full screen mode. This change uses the same fullscreen feature when toggling fullscreen with Alt+Enter or the toolbar option.
> Fix Mac OS full screen

- src/archutils/Darwin/SMMain.mm
This backports the recent fullscreen fix for macOS on the _master_ branch to the _5_1-new_ branch.   See: 281d36f05397752b8ad445631b9144853ea34998 
Credit goes to @aeubanks  for the original fix.
> backport macOS fullscreen fix to 5_1-new

- Docs/Luadoc/Lua.xml
- Docs/Luadoc/LuaDocumentation.xml
- src/PlayerStageStats.cpp
These two methods allow one to set the current stage's possible and actual dance points.
This would allow one to implement score 'bonuses' in simfiles with scripting, or have a minigame simfile (an example would be UKSRT8's "Sort Game") be able to have an actual score instead of 0%
Like the SetScore and SetCurMaxScore functions, a negative amount can't be used as input.
> Implemented SetActualDancePoints & SetPossibleDancePoints

- src/Style.cpp
Edit mode playback would crash if you pressed any keys not mapped.
This includes starting it with "P" if "P" is not mapped.
Problem was Style::GameInputToColumn didn't check for invalid inputs.
> Fix crash in edit play mode

- src/arch/Lights/LightsDriver_Linux_PIUIO_Leds.cpp
PIUIO pad lights on itg2 dedicab were off by one NUM_GameButton (gb) causing the wrong lights to be triggered when stepping on panels. added another nullptr as a quick fix.
> Fix pad button to light offset

- src/BitmapText.cpp
- src/BitmapText.h
```lua
self:strokecolor(fetch_color("accent.red"), 0)
:strokecolor(fetch_color("accent.green"), 1)
:strokecolor(fetch_color("accent.blue"), 2)
:strokecolor(fetch_color("accent.yellow"), 3)
```
No id or an id outside the 0-3 range sets all stroke colors.
> Allow multiple stroke colors, similar to multiple diffuse colors.

- src/MusicWheelItem.cpp
A short jaunt through the code leading up to the crash.
ScreenSelectMusic.cpp, BeginScreen:
```c++
PlayCommand( "Mods" );
m_MusicWheel.BeginScreen();
```
That PlayCommand goes to this metric:
_fallback/metrics.ini
```
[ScreenSelectMusic]
ScreenModsCommand=setupmusicstagemods
```
Which goes to _fallback/Scripts/02 StageMods.lua.  That function sets the steps for each player:
```lua
for pn in ivalues(GAMESTATE:GetHumanPlayers()) do
GAMESTATE:SetCurrentSteps( pn, steps )
GAMESTATE:GetPlayerState(pn):SetPlayerOptions( "ModsLevel_Stage", po )
GAMESTATE:SetPreferredDifficulty( pn, difficulty )
MESSAGEMAN:Broadcast( "PlayerOptionsChanged", {PlayerNumber = pn} )
end
```
MusicWheelItem is subscribed to the CurrentSteps*Changed message, so that goes to MusicWheelItem.cpp, HandleMessage.
```c++ …
```
> Fix extra stage MusicWheelItem crash

- src/archutils/Win32/mapconv.cpp
- src/rage/RageColor.hpp
- src/rage/RageMatrix.cpp
- src/rage/RageMatrix.hpp
- src/rage/RageString.cpp
Hello!
I'm a member of the Pinguem.ru competition on finding errors in open source projects. A list of bugs, found using PVS-Studio analyzer:
- [V654](https://www.viva64.com/en/w/v654/) The condition 'j < 4' of loop is always true. ragematrix.hpp 65
- [V533](https://www.viva64.com/en/w/v533/) It is likely that a wrong variable is being incremented inside the 'for' operator. Consider reviewing 'i'. ragematrix.hpp 65
- [V576](https://www.viva64.com/en/w/v576/) Incorrect format. Consider checking the third actual argument of the 'sscanf' function. A pointer to the unsigned long type is expected. mapconv.cpp 144
- [V576](https://www.viva64.com/en/w/v576/) Incorrect format. Consider checking the third actual argument of the 'sscanf' function. A pointer to the unsigned long type is expected. …
> Eliminate warnings/errors found by PVS-Studio analyzer

- Themes/_fallback/Scripts/04 menu.lua
- Themes/default/BGAnimations/ScreenNestyPlayerOptions overlay.lua
- Themes/default/BGAnimations/ScreenOptionsTheme overlay.lua
- Themes/default/Scripts/02 theme_config.lua
This fixed the two_direction menu input mode, and adds a config option to the default theme.
two_direction_with_select feels weird in use.
Left and right interact or adjust.
Start is up, not interact.  Select is down.
I don't know what the best behavior is for two_direction_with_select.
> Add menu input mode choices to default theme config.

- src/NoteDisplay.cpp
- src/NoteDisplay.h
ProgressAlternate is basically the same as Progress, except that notes on a frame boundary (for example, if there are 4 frames, notes at 0, 0.25, 0.5, and 0.75 beats) use the previous frame instead. This matches DDR's vivid and rainbow behavior.
> Add NoteColorType ProgressAlternate

- Themes/_fallback/Scripts/02 lua_config_system.lua
The other side of #1629.  Slightly different, this puts the theme name in the prefix when creating the object.
If default creates config objects, and the player uses home, the config will save in default_config/ instead of home_config/.
> Set save prefix in lua config when creating the config object

- Themes/_fallback/Scripts/02 ThemePrefs.lua
- src/ThemeManager.cpp
#1628 
ThemePrefs doesn't work right when a theme falls back on a theme that uses ThemePrefs.
02 ThemePrefs.lua has a detailed description of how the problem occurs.
Two ways to resolve this:
1. Require every theme that falls back on another theme to call ThemePrefs.Init at the end of its scripts.
Problem: A theme can't finish setting up the prefs it creates.
2. Make ThemePrefs use the actual theme the player chose.
Problem: Prefs are now saved under a different section name, so they have to be migrated.  This can be eased by making a screen or menu that uses ThemePrefs.CopyPrefsFrom, and have the player to pick a theme to copy prefs from.
> ThemePrefs use chosen theme

- src/CMakeData-arch.cmake
- src/arch/InputHandler/InputHandler_SDL.cpp
- src/arch/InputHandler/InputHandler_SDL.h
- src/arch/LowLevelWindow/LowLevelWindow_SDL.cpp
- src/arch/arch_default.h
Adds SDL2 input support and sets it as the default for linux. There might be some finishing touches to do here but I have been sitting on this for almost a year so I want to at least get it out for comment. For example: should this be the new default for linux? I like SDL2 for the hot plugging and have been using this for pad and keyboard since last year but I cannot guarantee it will behave exactly the same for everyone.
When I started working on this I did encounter a key repeat bug for linux in SDL 2.0.5: https://bugzilla.libsdl.org/show_bug.cgi?id=3472. Since returning to this I have not been able to reproduce. It seems likely one of the many distribution updates I applied since then resolved the issue.
Based on old SDL input code from 6a1db3af035ae2ca96ed3f80530cb69e9561087c.
Thanks …
> SDL2 input

- StepmaniaCore.cmake
- src/CMakeData-os.cmake
- src/RageDisplay.cpp
- src/RageDisplay_D3D.cpp
- src/arch/InputHandler/InputHandler_DirectInput.cpp
- src/arch/InputHandler/InputHandler_DirectInputHelper.cpp
- src/arch/LowLevelWindow/LowLevelWindow_Win32.cpp
- src/archutils/Win32/DirectXErrorList.h
- src/archutils/Win32/DirectXGuids.cpp
- src/archutils/Win32/DirectXHelpers.cpp
- src/archutils/Win32/DirectXHelpers.h
- src/archutils/Win32/ErrorStrings.h
Replaced most of the things missing from the Windows SDK version of the DirectX APIs so Stepmania can be built without needing the (old and deprecated) DirectX SDK.
One missing piece to still replace: d3d screenshot. The previous implementation used D3DX to copy/convert the backbuffer to RGBA. But D3DX was removed when DirectX was moved into the Windows SDK.
> Build with Windows SDK instead of DirectX SDK

- src/ezsockets.cpp
Without this sometimes an attempt at a connection hangs and completely stops the program (VERY annoying in fullscreen) in the recv function.
> Add timeout to smo sockets

- src/BitmapText.cpp
- src/Font.h
Currently only identical glyphs are merged into one DrawQuads call.
This fixes the comparison so that all glyphs with the same texture can
be merged, which greatly improves the font rendering performance.
> Improve DrawQuads batching in the font render.

- src/arch/Threads/Threads_Pthreads.cpp
- src/arch/Threads/Threads_Pthreads.h
Use pthread_setname_np to set the thread name.
This is useful to see the threads in top and other tools, e.g. 'top -H -p $(pidof stepmania)'.
Since At most 16 characters are allowed and some stepmania threads have longer names, there are two fallbacks to truncated the name:
If the name is of the form "Worker thread (name)", then "(name)" is used.
Otherwise long names are truncated by combining the first 6 and last 7 characters of the name with ".." as an ellipsis indicator in the middle.
> Propagate thread name to Linux pthread name.

- src/ArrowDefects.cpp
- src/ArrowDefects.h
Whoops.
Also moved tornado init to happen whenever the notefield gets new column positions from the noteskin, and renamed the scaling variables used to convert to/from the acos range.
> Fix tornado column clamping

- src/ScreenHowToPlay.cpp
- src/TimingData.cpp
#1656 also occurs in master, with the default theme.
The underlying cause is probably the same on the 5_1-new branch, though TimingData has a different structure so the commit can't be applied directly.
If you want to make ScreenHowToPlay easy to reach for testing, edit this into a screen:
```
t[#t+1]= Def.Actor{
OnCommand= function(self)
SCREENMAN:GetTopScreen():AddInputCallback(
function(event)
if event.type == "InputEventType_FirstPress" and
event.DeviceInput.button == "DeviceButton_n" then
SCREENMAN:GetTopScreen():SetNextScreenName("ScreenHowToPlay")
:StartTransitioningScreen("SM_GoToNextScreen")
end
end)
end
}
```
> Make ScreenHowToPlay clear its personal song from globals when exiting

- src/NoteField.cpp
- src/ScreenGameplay.cpp
This should take care of issue #1678 in the way that kyzentun mentioned.
> Moved display zbuffer clear to after notefields are drawn

- src/LightsManager.cpp
- src/LightsManager.h
- src/StepMania.cpp
- src/arch/Lights/LightsDriver.cpp
- src/arch/Lights/LightsDriver.h
- src/arch/Lights/LightsDriver_Export.cpp
- src/arch/Lights/LightsDriver_LinuxParallel.cpp
- src/arch/Lights/LightsDriver_Linux_PIUIO.cpp
- src/arch/Lights/LightsDriver_SextetStream.cpp
- src/arch/Lights/LightsDriver_SystemMessage.cpp
- src/arch/Lights/LightsDriver_Win32Parallel.cpp
This will avoid a crash caused by the fact LIGHTSMAN is destroyed
after the other MAN objects
As mentioned in #1661 the order of destruction could be changed to allow reset to work, but I don't think it's a big enough problem to warrant what (I assume) would be a fairly complex change
> Avoid crash in ~LightsDriver_SystemMessage

- src/arch/InputHandler/InputHandler_X11.cpp
- src/arch/InputHandler/InputHandler_X11.h
The X11 XKeyEvent structure (and others) include a timestamp
field, with 1ms resolution.
This was previously ignored causing the input timestamps to be
set to the middle of each frame.
If the timestamps are passed through then the event timestamps are
not coupled to the framerate and the polling issues are resolved.
So far these changes have been tested on Linux Mint, for IPAC, JPAC, and keyboard. No issues have been identified (and several quads have been achieved without any of the previously noted polling issues)
> Preserve event timestamps in X11 input driver

- Docs/Luadoc/LuaDocumentation.xml
SONGMAN:GetCoursesInGroup() actually takes two arguments, a string and a boolean, but the existing Lua Docs only mention the first.  This fixes that.
> fix LuaDoc for SONGMAN:GetCoursesInGroup()

- Themes/_fallback/metrics.ini
- src/DancingCharacters.cpp
The Dancing Characters in SM is quite limited in terms of settings, so I thought of making it more open for people to customize for their themes.
These changes allow for more things to control in terms of the camera and lighting. All being stored in [DancingCamera] located at the bottom of the fallback.ini file.
Here's some images showing the stuff can do with these changes.
> Broader Dancing Character Control for themers

- CMake/DefineOptions.cmake
We want to fix Travis and most users wont use this, will add a proper fix in the future, even if I have to write my own version of libmmmagic myself
> Disable Minimaid by default

- src/GameLoop.cpp
- src/GameLoop.h
- src/PrefsManager.cpp
- src/PrefsManager.h
- src/RageSoundManager.cpp
- src/RageSoundManager.h
- src/arch/Sound/RageSoundDriver.h
- src/arch/Sound/RageSoundDriver_Generic_Software.cpp
Leaves default buffer underrun behavior in tact unless user specifies a preference to fix the clamp. Some audio drivers clamp at less than expected values. SM5 expects to have a PROGRAM_OPEN_LENGTH running total of samples played to find it's position. This fixes it resolving issue #1459 ; This does NOT fix problems, for example, with direct sound itself. If you overflow your sound driver's sample count, directsound will murder itself and your entire computer's audio will be messed up until you reboot (if your OS uses directsound for audio output like windows 10). Ultimately, this is a vendor driver problem. The safest way to use this patch on windows is with waveout. This might not be an issue on other OSes, but just in case, it's portable to them too.
> Fix audio drivers with a low sample count maximum value

- src/arch/Sound/RageSoundDriver_AU.cpp
As I promised in #1734, I tested the commits from #633 against the current *5_1-new* branch, and am now (re)submitting them as a pull request.  
These commits clean up about a dozen macOS AudioDevice deprecation warnings.  They were originally made by GitHub user teejusb in 2015 to the master branch (currently thought of as SM5.2).
I `cherry-pick`'d them in, I built, and I played a game without encountering any problems.  If issues are reported in the future, this can always be reverted.
> backport macOS AudioDevice cleanup into 5_1-new

- src/arch/InputHandler/InputHandler_MacOSX_HID.cpp
Mixing Carbon and CoreFoundation/Cocoa isn't nice.
This fixes #1417
> Fix detection of shift key on macOS

- CMake/SetupFfmpeg.cmake
- CMake/SetupOggVorbis.cmake
- StepmaniaCore.cmake
- src/CMakeLists.txt
- src/arch/InputHandler/InputHandler_MacOSX_HID.cpp
- src/archutils/Darwin/Crash.cpp
This fixes the Xcode build and also makes the "Unix Makefile" generator work properly for the Ogg/Vorbis oddness. You can do these side-by-side:
```
cd Build
cmake -G Xcode ..
xcodebuild  # or `open StepMania.xcodeproj/` and click Build in Xcode UI
```
```
mkdir Build2
cd Build2
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j9
```
This fixes detecting the yasm binary for ffmpeg. And I adjusted the tabs in `InputHandler_MacOSX_HID.cpp` since they went in as spaces in my last PR.
It is recommended that `-DCMAKE_BUILD_TYPE` always get passed in the Makefile case, but if left blank it will work too.
I will try and figure out Ninja support in the future. It has the same problem as Makefile but the target computation is not done earlier than how Make does it.
> Fix Xcode build; bump minimum version of macOS

- Themes/_fallback/metrics.ini
- src/GrooveRadar.cpp
- src/ScreenSelectMusic.cpp
- src/ScreenSelectMusic.h
DDR uses Up/Down to select difficulty.
PIU uses Left/Right to select difficulty.
Thus these should be remappable for themers.
Because the Up/Down to cancel mapping would conflict with the Up/Down to change difficulty mapping, these also need to be remappable. 
P.S. I tested this and it works
> Make TwoPartSelect remappable

- StepmaniaCore.cmake
To address #1803 
HAS_XX is used elsewhere in the project to select optional sources,
will only be true if the lib is available on the system, and the
user asked to use it.
> CMake: Fix selection logic for sound libraries

- CMake/DefineOptions.cmake
Fixes #1848.
As PulseAudio is widely adapted it might make sense to enable it by default for builds on Linux.
> 5.1: Build with PulseAudio by default

- StepmaniaCore.cmake
Fixes #1859.
Uses CMake's FindModule for OpenGL.
This depends on #1851 (on my system I can't build without it) and is thus marked as draft.
Should this target `5_1-new` as well?
>  Linux: Use GLVND if available
