.gitignore

May have been from cmake testing.

Ignore generated .dia files?

---

Xcode/Info-StepMania.plist

These are two minor updates to the Xcode project that show up in the .app's metadata.

Xcode updates

---

src/HighScore.cpp
src/HighScore.h
src/Inventory.cpp
src/Inventory.h
src/LuaManager.cpp
src/Player.cpp
src/Player.h
src/PlayerStageStats.h
src/ScoreKeeperNormal.cpp
src/ScreenGameplay.cpp
src/StageStats.cpp
src/StageStats.h

also includes 64-bit sum calculation and new milestones.

Combo and score stuff, take 2

---

extern/jsoncpp/libjson-net2011.vcxproj
extern/jsoncpp/libjson-net2011.vcxproj.filters
extern/jsoncpp/src/lib_json/json_reader.cpp
extern/jsoncpp/src/lib_json/json_value.cpp
extern/jsoncpp/src/lib_json/json_writer.cpp
src/StepMania-net2011.vcxproj
src/StepMania-net2011.vcxproj.filters
src/sm5-net2011.sln

Please confirm this compiles on your environments: had to modify extern files back to what I beileve they should have been to begin with.

Finish the library job properly: JSON moved in VS2012.

---

Docs/Themerdocs/Examples/Example_Actors/BitmapText.lua
Docs/Themerdocs/Examples/Example_Actors/Quad.lua
Docs/Themerdocs/Examples/Example_Actors/RollingNumbers.lua

These were added to the Example_Actors folder. More to come.

Add BitmapText, Quad, and RollingNumbers examples.

---

NoteSkins/dance/midi-note-3d/NoteSkin.lua
NoteSkins/dance/midi-note/NoteSkin.lua

putting back roll heads

---

Themes/default/Languages/es.ini

Sorry! This one was left behind.

Spanish small update

---

Themes/_fallback/Languages/nl.ini
Themes/default/Languages/nl.ini

This is the first time I'm doing a fork and pull request and stuff, hope I'm doing it right haha.
Loads of edits, and added all the missing lines as specified in nl_missing.ini (though I noticed and added a couple of missing ones as well that weren't mentioned in the nl_missing ini).
Commentary on made changes to _fallback here, just to share some insight to why I changed some things: http://pastebin.com/7V3av97c
As I progressed, I started making less and less notes. I decided to not do this for the default theme at all because most of my motivations are similar to the changes I made in _fallback.
I'm sure there's still some inconsistencies and little mistakes in there, I've yet to check out the appearance of the translations in-game. I'll happily continue to maintain the Dutch …

Dutch translations, polishing and filling in missing lines.

---

src/Difficulty.cpp
src/GameConstantsAndTypes.cpp
src/IniFile.cpp
src/IniFile.h
src/NotesLoaderSM.cpp
src/NotesLoaderSM.h
src/NotesLoaderSSC.cpp
src/PrefsManager.cpp
src/RageTimer.h

Reverts stepmania/stepmania#494

Revert "Improved NotesLoaderSSC and NotesLoaderSM"

---

Themes/_fallback/Languages/fr.ini
Themes/default/Languages/fr.ini

Worked some on the default file, created the fallback one from English. Did a bit of shorting on the fallback file so that it's easier to find things based on where they show.

French translation

---

Docs/Themerdocs/Examples/Example_Actors/ActorFrameTexture.lua
src/RageDisplay.h
src/RageDisplay_OGL.cpp
src/RageDisplay_OGL.h
src/RageTextureRenderTarget.cpp
src/RageTextureRenderTarget.h

I feel like a lot of people do not understand what these things do but I am overly in love with them so I thought I'd fix a few bugs and give you some examples.

Actor frame texture

---

src/StepMania-net2013.vcxproj
src/StepMania-net2013.vcxproj.filters
src/ver.h

This should compliment 7ac547a5.

Fix compilation for cmake-less 2013 users.

---

CMakeLists.txt
src/CMakeLists.txt

Thanks for the assist teleshoes.

Don't have ffmpeg's download take forever.

---

src/GameConstantsAndTypes.h
src/NoteDataUtil.cpp
src/NoteDataUtil.h
src/RageTimer.cpp
src/RageTimer.h
src/RageUtil.cpp
src/RageUtil.h
src/ScreenEdit.cpp
src/Song.cpp
src/Song.h

In general, this makes Stepmania avoid looking in the song directory at all if the song is in the cache, in order to load songs faster.  All the RadarValue calculations were also rolled into one to reduce the time needed to build the cache.
Song::TidyUpData was rearranged a lot to reduce the number of times it looks through the song directory, particularly the portion that deals with finding images.  It still goes through the song directory more than once, but it's been cut down a lot.
Known problems:
The new function for calculating RadarValues finds a slightly lower value for Voltage than the old GetVoltageRadarValue function did.  I can't figure out why and I've been staring at the code for too long to be able to make progress on it anymore.  If nobody else cares enough to examine the …

More aggressive caching.

---

src/Actor.cpp
src/Course.cpp
src/RageLog.cpp
src/RageLog.h
src/RageTimer.h
src/RageUtil.cpp
src/Song.cpp
src/Song.h
src/SongCacheIndex.cpp
src/SongCacheIndex.h
src/SongManager.cpp
src/SongManager.h

More things that I found that were wasting time during loading.  This should be the last bit of loading speed up stuff, it seems every last bit of time has been wrung out of it.
The commit message has an overview of what was changed.
One thing I noticed was that I got some speedup out of disabling the banner cache with its preference, and this seemed to make no difference in select music, so does the banner cache even have a point anymore?

Various changes to speed up start up time

---

src/GameConstantsAndTypes.cpp
src/GameConstantsAndTypes.h
src/GrooveRadar.cpp
src/NoteDataUtil.cpp
src/NoteDataWithScoring.cpp
src/NoteDataWithScoring.h
src/NotesLoaderSSC.cpp
src/NotesLoaderSSC.h
src/Song.cpp
src/Song.h
src/TimingData.cpp

This adds a new radar category for the number of notes, uncaps SVAFC categories, and fixes a couple bugs.

RadarCategory_Notes, uncapping and fixes to radar calculation.

---

Themes/_fallback/Languages/nl.ini

Last two lines that were left untranslated

---

src/arch/InputHandler/LinuxInputManager.cpp

Hi StepMania maintainers, I didn't see any documentation about how you want patches submitted so I'm just sending a pull request.  This patch fixes detection of my dance pad.

getDevice: Do not read a dirent after calling closedir.

---

src/Actor.cpp
src/Actor.h
src/ArrowEffects.cpp
src/ArrowEffects.h
src/CubicSpline.cpp
src/CubicSpline.h
src/Model.cpp
src/Model.h
src/NoteDisplay.cpp
src/NoteDisplay.h
src/NoteField.cpp
src/NoteField.h
src/Player.cpp
src/RageTextureManager.cpp
src/RageTextureManager.h
src/RageTimer.h
src/ReceptorArrowRow.cpp
src/ScreenGameplay.cpp
src/Sprite.cpp
src/Sprite.h

Not measurably successful at improving performance, but I still consider these improvements over the way things were done before.
Read the commit message for an overview of the changes.

Attempts to improve performance

---

Themes/_fallback/Languages/ja.ini

Add 2 lines to /Themes/_fallback/Languages/ja.ini:
[OptionExplanations] AllowMultipleToasties
[OptionTitles] AllowMultipleToasties

Update Japanese translation

---

src/NotesLoaderBMS.cpp

* removal of commented code
* if body on line 899 enclosed in curly brackets like a proper person
* space indents changed to tabs

Tidying up notesloaderBMS.cpp per kyzentun's request

---

src/BannerCache.cpp
src/Foreach.h
src/InputFilter.cpp
src/LuaManager.cpp
src/NoteData.cpp
src/NoteData.h
src/NotesWriterJson.cpp
src/PrefsManager.cpp
src/Profile.cpp
src/RageLog.cpp
src/RageTextureManager.cpp
src/RageUtil.cpp
src/SongManager.cpp
src/archutils/Win32/CrashHandlerNetworking.cpp

Remove FOREACHM_CONST.

---

.travis.yml
src/CMakeLists.txt
src/arch/ArchHooks/ArchHooks.h

If any clang users run into problems, remember to have libc++ and libc++abi set up.

Have clang and libc++ working.

---

src/Background.cpp
src/Course.cpp
src/Foreach.h
src/GameState.cpp
src/NoteField.cpp
src/NotesWriterSM.cpp
src/OptionsList.cpp
src/RageDisplay_GLES2.cpp
src/RageDisplay_OGL.cpp
src/RageInputDevice.cpp
src/RageSoundManager.cpp
src/ScreenMessage.cpp
src/SongManager.cpp

Verified on Linux locally. Hope TeamCity behaves.

Remove the FOREACHM constant.

---

Docs/Changelog_sm5.txt

Per Shakesoda's request.
I'll do this with every pull request I make from now on.

Updated the changelog with all the new changes I've made

---

src/CMakeLists.txt
src/version_updater/version.hpp.in

My bad. The new cmake code doesn't work well with Windows platforms, so I reverted this. I'll do further testing with a Windows node I have hanging around. In the meantime, this'll do the trick.

Restore VersionUpdater for Windows

---

README.md

Update README.md to fix broken link to CMake

---

src/Actor.cpp
src/ActorMultiTexture.cpp
src/ActorMultiVertex.cpp
src/BitmapText.cpp
src/CourseContentsList.cpp
src/GraphDisplay.cpp
src/LifeMeterBattery.cpp
src/MessageManager.cpp
src/NoteDataWithScoring.cpp
src/NoteDisplay.cpp
src/NoteField.cpp
src/NotesLoaderBMS.cpp
src/NotesLoaderJson.cpp
src/OptionRowHandler.cpp
src/Player.cpp
src/PlayerOptions.cpp
src/PlayerStageStats.cpp
src/Profile.cpp
src/RageUtil.cpp
src/SampleHistory.cpp
src/ScreenEdit.cpp
src/SongManager.cpp
src/SongUtil.cpp
src/StepMania.cpp
src/ThemeManager.cpp
src/TimingSegments.cpp
src/arch/InputHandler/InputHandler_DirectInput.cpp
src/arch/Sound/RageSoundDriver_WDMKS.cpp

These may exist on non-Windows as well.

Address some warnings on Windows.

---

Themes/_fallback/BGAnimations/ScreenOverscanConfig overlay.lua
Themes/_fallback/metrics.ini

Now you can exit OverscanConfig safely.

Fixed input function on ScreenOverscanConfig

---

Themes/_fallback/Languages/ja.ini

Fixed some typo and standardized expression.

Fix Japanese translation:

---

src/CMakeLists.txt

If Travis builds this, then we know it is solid.

Use list(FIND) to have more flexible lists.

---

Docs/Luadoc/Lua.xml
Docs/Luadoc/LuaDocumentation.xml
src/RageMath.cpp
src/RageMath.h

Had to write this anyway so that I could design bezier tweens with less trial and error, so here it is.

Added lua interface for using bezier curves.

---

Build/README.md

I described cmake command execution because it's difficult to understand how to use.
By add this sentence, I expect that all of people can more easily to do CMake Installation.

Add example information: Build/README.md. 

---

src/GameConstantsAndTypes.cpp
src/GameConstantsAndTypes.h
src/Player.cpp

Pump holds do have a little bit of leeway when it comes to letting go and putting your foot back on as proven by [WinDEU's demonstration of Dignity S20](https://www.youtube.com/watch?v=P2Fw9KPyHIg&feature=youtu.be&t=30).
The value used was determined by two video sources: the one mentioned above and a private one sent to me involving a different song/chart combination. 200ms is a rough estimate for what works. There may be other allowed values.

Partial revert of b61e878.

---

src/archutils/Win32/arch_setup.h

This commit makes use of math functions implemented in Visual Studio 2012 and 2013 to prevent redefinition.
Edit: And also byte swap functions implemented in Visual Studio .NET 2003.

Use Visual Studio implemented functions.

---

.install-cmake.sh
.travis.yml

Alledgedly, we'll get faster builds and performance. Considering how complex this repository is, it's worth trying. Note that sudo calls are not allowed with this container format at this time.

Switch to travis's container infrastructure.

---

StepmaniaCore.cmake
src/archutils/Win32/arch_setup.h
src/config.in.hpp

Note that this does NOT allow linking. Dependent on #778 for that.

Allow VS2015 to compile StepMania.

---

src/FileDownload.cpp
src/RageSoundReader_WAV.cpp
src/RageUtil.cpp

For most areas, the call to `c_str()` is plenty.
For `RageUtil`, it's just a matter of new and delete.

Remove the need for the RString buffer.

---

src/NoteDisplay.cpp

This PR will fix the following issues.
https://github.com/stepmania/stepmania/issues/738

 fix draw hold body inactive texture bug 

---

src/CMakeLists.txt
src/CMakeProject-mapconv.cmake

Clearing the cmake cache may be required.

Restore mapconv post operations.

---

.gitignore
.gitmodules
StepmaniaCore.cmake

Yes, this means ffmpeg will need to be built again.
However, this is more the git way.

Switch to submodules for ffmpeg.

---

src/RageSoundReader_WAV.cpp
src/RageUtil.cpp
src/archutils/Win32/CrashHandlerChild.cpp
src/archutils/Win32/CrashHandlerNetworking.cpp
src/archutils/Win32/ErrorStrings.cpp

...we seriously need to use a standard <string>.
*glares at Yaniel*

Remember to fill in new char's.

---

CMake/CPackSetup.cmake
CMake/Modules/NSIS.template.in
CMake/SMDefs.cmake
StepmaniaCore.cmake

This brings it closer in-line to what we used prior to CMake.

Modify the NSIS template for a better installer.

---

Docs/Luadoc/Lua.xml
Docs/Luadoc/LuaDocumentation.xml
Docs/Themerdocs/5.1_incompatibilities/RollingNumbers.md
Themes/_fallback/metrics.ini
src/BitmapText.h
src/LuaBinding.h
src/Player.cpp
src/RollingNumbers.cpp
src/RollingNumbers.h

Replacement for the failed #733 PR.

Better RollingNumbers

---

CMake/SetupFfmpeg.cmake
StepmaniaCore.cmake
src/CMakeData-arch.cmake
src/arch/InputHandler/InputHandler_Win32_Pump.cpp
src/archutils/Win32/arch_setup.h
src/config.in.hpp

The biggest obstacle right now deals with FFMPEG. I insist on being able to utilize the git clone/submodule (5_1_0) section. I'm just struggling with the commands.
As part of this commit, some linux files are restored in the compilation chain. This is for consistency with the old Makefile approach.
Assistance will be needed at this point to complete MinGW support.

Bring us closer to working with MinGW again.

---

src/RageDisplay_D3D.cpp

...apparently this still works?
Either that or I had OpenGL still on.

Fix windows build.

---

src/Actor.cpp
src/Actor.h
src/ActorMultiTexture.cpp
src/ActorMultiTexture.h
src/ActorMultiVertex.h
src/BGAnimationLayer.cpp
src/Background.cpp
src/Banner.cpp
src/BitmapText.cpp
src/CMakeProject-rage-test.cmake
src/CMakeProject-rage.cmake
src/Font.h
src/GraphDisplay.cpp
src/GraphDisplay.h
src/NoteDisplay.cpp
src/NoteField.cpp
src/RageTexture.cpp
src/RageTexture.h
src/RageTypes.h
src/ScreenDebugOverlay.cpp
src/ScreenDimensions.h
src/ScreenStatsOverlay.cpp
src/ScrollBar.cpp
src/Sprite.cpp
src/Sprite.h
src/StreamDisplay.cpp
src/WorkoutGraph.cpp
src/rage/RageRect.hpp
src/tests/RageRectTest.cpp

Strange: apparently we don't use `RectI` anywhere.

Move and propertly specialize the Rect class.

---

StepmaniaCore.cmake
src/ArrowEffects.cpp
src/GraphDisplay.cpp
src/Player.cpp
src/PlayerStageStats.cpp
src/RageDisplay.cpp
src/RageMath.cpp
src/RageSoundReader_Resample_Good.cpp
src/RageUtil.cpp
src/config.in.hpp

Again, c++11 should be utilized.

Other math related ___f functions eliminated.

---

CMake/DefineOptions.cmake

Reverts stepmania/stepmania#832

Revert "Default to GPL off for ffmpeg."

---

.appveyor.yml

Using appveyor for the initial tryout. Currently dealing with issues on getting github to recognize the pull request commits.
The token in place is a double secured token: it can be replaced quickly if necessary.

Get continuous integration working on windows.

---

src/Actor.cpp
src/RageDisplay.cpp
src/RageDisplay_D3D.cpp
src/RageDisplay_OGL.cpp
src/RageMath.cpp
src/RageMath.h
src/rage/RageMatrix.cpp
src/rage/RageMatrix.hpp

Saving the ones involving PI for another day.

Move some matrix math calls to Rage.

---

StepmaniaCore.cmake
src/AnnouncerManager.cpp
src/InputMapper.cpp
src/NetworkSyncManager.cpp
src/NoteSkinManager.cpp
src/ScreenOptionsMasterPrefs.cpp
src/archutils/Win32/arch_setup.h
src/config.in.hpp
src/global.h

On a side note, better to default to linux names when possible.

Use cmake to determine which string func we need.

---

StepmaniaCore.cmake
src/Actor.cpp
src/ArrowEffects.cpp
src/GraphDisplay.cpp
src/GrooveRadar.cpp
src/ModelTypes.cpp
src/NoteDisplay.cpp
src/RageDisplay.cpp
src/RageMath.cpp
src/RageMath.h
src/RageSoundReader_Resample_Good.cpp
src/Tween.cpp
src/config.in.hpp
src/rage/RageMath.hpp

This even works in VS2015.
If this fails in Linux, guess we must enforce c++14.

Replace the PI macros with a constexpr.

---

src/RageSoundReader_WAV.cpp

Fix keysounds (and other WAV files).

---

src/archutils/Darwin/arch_setup.h
src/archutils/Unix/arch_setup.h

In all seriousness, no need for this definition anymore.

FINALLY shut ffmpeg up!

---

CMake/Modules/FindDl.cmake
StepmaniaCore.cmake
src/CMakeLists.txt
src/archutils/Unix/BacktraceNames.cpp
src/archutils/Unix/BacktraceNames.h
src/archutils/Unix/CrashHandlerChild.cpp

* Properly detect and utilize libdl.
* Set the backtrace method appropriately.
* Remove an unused backtrace format. No references existed.

Backtrace stuff ahoy!

---

src/AdjustSync.cpp
src/AdjustSync.h
src/ScreenGameplaySyncMachine.cpp
src/ScreenSyncOverlay.cpp

There are potential linker errors if this is not done.

Ensure OFFSET_SAMPLE_COUNT is defined in the cpp.

---

src/Actor.cpp
src/ActorUtil.cpp
src/AnnouncerManager.cpp
src/BGAnimationLayer.cpp
src/Course.cpp
src/CourseLoaderCRS.cpp
src/Font.cpp
src/GameSoundManager.cpp
src/InputMapper.cpp
src/LyricsLoader.cpp
src/ModIcon.cpp
src/NotesLoaderDWI.cpp
src/NotesLoaderJson.cpp
src/NotesLoaderKSF.cpp
src/NotesLoaderSM.cpp
src/NotesLoaderSMA.cpp
src/NotesLoaderSSC.cpp
src/RageUtil.cpp
src/ScreenInstallOverlay.cpp
src/Song.cpp
src/SongManager.cpp
src/ThemeManager.cpp
src/arch/Lights/LightsDriver_Linux_PIUIO.cpp
src/arch/Lights/LightsDriver_Linux_PIUIO_Leds.cpp
src/arch/MemoryCard/MemoryCardDriverThreaded_Windows.cpp

No logging errors or exceptions were seen during these tests.

Use our ci_ascii_string, not EqualsNoCase.

---

src/Actor.cpp
src/ActorUtil.cpp
src/BGAnimation.cpp
src/CourseLoaderCRS.cpp
src/CourseUtil.cpp
src/CsvFile.cpp
src/IniFile.cpp
src/InputQueue.cpp
src/MemoryCardManager.cpp
src/NetworkSyncManager.cpp
src/NotesLoader.cpp
src/NotesLoaderSMA.cpp
src/RageFileDriverDirectHelpers.cpp
src/RageFileManager.cpp
src/ScreenBookkeeping.cpp
src/ScreenSelect.cpp
src/Song.cpp
src/SongManager.cpp
src/SongUtil.cpp
src/Steps.cpp
src/ThemeManager.cpp
src/XmlToLua.cpp
src/archutils/Unix/BacktraceNames.cpp

Again, trying to migrate away from StdString.

All .Left() calls replaced with head/starts_with.

---

src/global.h

This commit may be ported to `master` most likely.

Allow LLVM to use branch prediction.

---

.travis.yml
CMake/DefineOptions.cmake
CMake/SetupFfmpeg.cmake

Yes, it is now possible to use a different number of jobs for ffmpeg and stepmania proper.

Allow customizing the number of jobs for ffmpeg.

---

.appveyor.yml
CMake/DefineOptions.cmake
src/CMakeLists.txt
src/CMakeProject-irc.cmake
src/irc/appveyor.cpp

This replaces #899 due to Github being a derp.

Add IRC feedback from Windows build servers. (Redo)

---

CMake/CMakeMacros.cmake
CMake/DefineOptions.cmake
StepmaniaCore.cmake

Happy now @Prcuvu? :stuck_out_tongue:

Default to linking with /MT instead of /MD for VS.

---

src/rage/RageString.cpp
src/rage/RageString.hpp
src/tests/RageStringTest.cpp

This will be utilized after the 5.0.10 release.

Prepare the new dedicated Rage::join method.

---

src/ActorFrameTexture.cpp
src/RageUtil.cpp
src/RageUtil.h

No need to do special windows handling anymore.

Use the fmt library for consistent lli usage.

---

CMake/DefineOptions.cmake
src/TimingData.cpp
src/config.in.hpp

For those with many songs, it gets annoying.

Allow optional logging of timing segment mods.

---

.travis.yml
src/irc/appveyor.cpp

Apparently #stepmania-devs is for discussion only.
...is this backwards?

Put the bots back in #stepmania.

---

.travis.yml

Thanks to [opencor](https://github.com/opencor/opencor) for the idea.

Restore compilation with Travis.

---

src/FontCharAliases.cpp
src/rage/RageString.hpp

We're using standard c++ with the `Rage::` items.

Remove the StdString comparison.

---

src/MessageManager.cpp
src/StepMania.cpp

This fixes a well-formed warning, but does it break anything?
It's not clear off hand. Having this up for discussion.

Instantiate MESSAGEMAN first.

---

src/archutils/Unix/X11Helper.cpp

My screen kept going into dpms mode, even while I was playing on keyboard.  So this disables dpms on startup.

Added code to disable x11 dpms on startup and restore it on exit.

---

src/Actor.cpp
src/ActorMultiVertex.cpp
src/ActorUtil.cpp
src/Background.cpp
src/BitmapText.cpp
src/LuaBinding.h
src/LuaManager.cpp
src/ModValue.cpp
src/NewField.cpp
src/NoteField.cpp
src/Player.cpp
src/RageUtil.cpp
src/Screen.cpp
src/ScreenEvaluation.cpp
src/ScreenGameplay.cpp
src/ScreenNetEvaluation.cpp
src/ScreenSelectMaster.cpp
src/TimingData.cpp
src/UnlockManager.cpp

Putting in a branch in case other wants to review first.

Resolve about half the remaining W4 warnings.

---

NewSkins/easyV2/notes.lua
NewSkins/exactV2/notes.lua

I'm dumb and forgot reverse

---

src/Course.cpp

The old algorithm for generating courses has a tendency to repeat songs.
This commit prevents that from happening. Songs will instead shuffle, and will
only repeat if the current song list has finished.
This is a partial fix, since for some reason, the method responsible
for getting all the songs in a song group is not doing its work properly.
That means for a course that's supposed to have a 100 songs, only 95 of them
would appear. The other 5 will never appear, and the last 5 will be a repeat
of the first 5 songs.

Partially fix song repetition in generated courses.

---

Themes/default/Languages/id.ini

Bahasa Indonesia now was added to the default theme
To let the non-English speaker in Indonesia understand some string that came with the theme.

Add Bahasa Indonesia to default theme

---

Themes/_fallback/BGAnimations/ScreenSelectProfile overlay.lua
Themes/_fallback/Languages/en.ini
Themes/_fallback/Languages/es.ini

Also, some line trimming shenanigans.

Properly translate # songs played.

---

src/archutils/Win32/arch_setup.h

Needs verification on AppVeyor.

Try removing some macros.

---

src/ActorMultiVertex.cpp
src/Bookkeeper.cpp
src/Model.cpp
src/NewSkinManager.cpp
src/NoteDisplay.cpp
src/RageFile.cpp
src/RageSoundReader_FileReader.cpp
src/RageUtil.cpp
src/ScreenOptions.cpp
src/ScreenSelectMusic.cpp
src/TitleSubstitution.cpp
src/arch/LoadingWindow/LoadingWindow.cpp

Only a few of the sane ones were handled this go-around.

Prevent potential garbage value checks.

---

src/arch/Lights/LightsDriver_Win32Minimaid.cpp

Prevent crashes from unconnected Mimimaid devices.

---

src/ScreenOptionsMasterPrefs.cpp

This adds item "1" in NumBackgrounds.

[ScreenOptionsMasterPrefs] Added 1 new item in NumBackgrounds

---

NewSkins/easyV2/receptors.lua
NewSkins/exactV2/receptors.lua

while the old receptor hack did work on windows, it didnt work on linux or mac, I fixed it now to work on all systems

ExactV2 and EasyV2 Receptor fixes 

---

Themes/_fallback/Scripts/03 DisplaySpecs.lua

The `03 DisplaySpecs.lua` script (introduced in #1018) contains a uninitialized-variable bug corrupting the table of aspect ratios supported by a given display, if that display reports a mode with a "non-standard" aspect ratio (not in the set {3:4, 1:1, 5:4, 4:3, 16:10, 16:9, 8:3}). This PR fixes that typo.

fix _fallback menu behavior for unrecognized aspect ratios

---

Docs/Themerdocs/actordef.txt

This should resolve issue #781.

clean up ./Docs/Themerdocs/ActorDef.txt

---

.appveyor.yml
src/LuaManager.h

* Fix Appveyor building.
* Squash casting warnings.

Minor improvements for Windows.

---

src/Player.cpp
src/Player.h

I think there might be one more little problem left to fix, but this actually gets most of them.

Improve PenalizeTapScoreNone

---

src/Background.cpp
src/Course.cpp
src/CourseUtil.cpp
src/GameState.cpp
src/MusicWheel.cpp
src/NoteDataUtil.cpp
src/NotesLoaderBMS.cpp
src/Player.cpp
src/RageUtil.cpp
src/RageUtil.h
src/RandomSample.cpp
src/ScreenDebugOverlay.cpp
src/ScreenEvaluation.cpp
src/ScreenNameEntryTraditional.cpp
src/ScreenOptionsCourseOverview.cpp
src/ScreenOptionsReviewWorkout.cpp
src/SongManager.cpp
src/StepMania.cpp
src/archutils/Win32/CrashHandlerNetworking.cpp
src/smpackage/ZipArchive/ZipArchive.cpp

Use the standard library one instead.

Remove custom Mersenne Twister

---

src/CMakeData-arch.cmake
src/arch/Lights/LightsDriver_PacDrive.cpp
src/arch/Lights/LightsDriver_PacDrive.h

LightsDriver=PacDrive and PacDrive32.dll in Program folder. Windows only.
You can get PacDrive32.dll from the PacDrive SDK available here: https://www.ultimarc.com/programming.html
Demonstration video: https://www.youtube.com/watch?v=IFN4Xc3aZ0w

Add PacDrive lights driver

---

src/Player.cpp

Fixes issue #1349 in the way that Kyzentun mentioned.

Fix oitg_zoom_mode

---

src/MusicWheel.cpp
src/RoomWheel.cpp
src/RoomWheel.h
src/ScreenNetRoom.cpp
src/ScreenNetRoom.h
src/ScreenNetSelectBase.cpp
src/ScreenNetSelectBase.h
src/ScreenNetSelectMusic.cpp
src/ScreenNetSelectMusic.h

NetRoom/SelectBase/Music lua objects. 
Scrolling with lua funcs and binded to ctrl+pg up/down (in netselectbase).
Show prev msgs, binded to pg up/down (in netselectbase)
Friendlist lua functions(Commented for now until https://github.com/stepmania/stepmania/pull/1393 gets merged).
Music wheel move and selectmusic screen's select current song lua func (Musicwheel and Roomwheel)
Chatbox visibility, input en/disabling and UserList visibility lua functions(in netselectbase)
Through lua chat scrolling with mouse wheel, musicwheel moving with mouse wheel and song selecting/sstarting with mouse clicks can be implemented(The same way it can be done in Etterna. An example can be seen in it's default theme Til Death in the files _chatbox and _mousewheelscroll and _mouseselect here: …

Features for some net screens

---

src/MessageManager.cpp
src/StepMania.cpp

Same as #1384 for 5_1-new branch, as requested.

Cherry-pick "Instantiate MESSAGEMAN first" to fix a crash in release build (5_1-new)

---

Docs/Luadoc/Lua.xml
Docs/Luadoc/LuaDocumentation.xml
src/ArrowDefects.cpp
src/ArrowDefects.h
src/PlayerOptions.cpp
src/PlayerOptions.h

Due to this being the 5.2 version of #1411 , refer to that for the modifiers added.

Add nITG's new move modifiers into ArrowDefects

---

src/Actor.cpp
src/ActorFrame.cpp
src/ActorUtil.cpp
src/DynamicActorScroller.cpp
src/GameCommand.cpp
src/LifeMeterBattery.cpp
src/LuaExpressionTransform.cpp
src/LuaManager.cpp
src/LuaManager.h
src/MenuTimer.cpp
src/NoteField.cpp
src/OptionRowHandler.cpp
src/PercentageDisplay.cpp
src/Profile.cpp
src/ScoreKeeperNormal.cpp
src/Screen.cpp
src/ScreenGameplay.cpp
src/ScreenSelectMaster.cpp
src/ScreenTextEntry.cpp
src/ThemeMetric.h
src/UnlockManager.cpp

As the title says.  A few simple changes.

Improve handling of errors in lua functions and speed up calls.

---

src/TimingData.cpp

Making sure the lookup table is rebuilt.
Relevant issues: 
#1335 
I thought there were more issues open for sync problems after changing timing data in edit or sync mode, but I can't find them now.

Fix sync bugs when timing data is changed in edit or sync mode

---

src/PlayerOptions.cpp

Allow spaces in noteskin names.

---

Docs/Luadoc/Lua.xml
Docs/Luadoc/LuaDocumentation.xml
src/PlayerStageStats.cpp

Since this is a port of #1527, the main details are there.

Implement SetDancePointLimits (5.2)

---

Data/Shaders/GLSL/Distance field.frag
Data/Shaders/GLSL/Distance field.vert
src/RageDisplay_OGL.cpp
src/RageTypes.cpp
src/RageTypes.h

The plan is to add support for distance field fonts, but this I feel is somewhat useful by itself. Tested and works.

Distance field EffectMode

---

Themes/_fallback/Languages/de.ini
Themes/_fallback/Languages/en.ini
Themes/_fallback/Languages/es.ini
Themes/_fallback/Languages/eu.ini
Themes/_fallback/Languages/fr.ini
Themes/_fallback/Languages/ja.ini
Themes/_fallback/Languages/nl.ini
Themes/_fallback/Languages/pl.ini
Themes/_fallback/Languages/zh.ini
src/ScreenEdit.cpp

ScreenEdit: Update shortcut list to include Jump to next/previous note

---

src/Profile.cpp

Increasing the profile songs higher.

MAX_PLAYER_STATS_XML_SIZE_BYTES -> songs -> 10000

---

.appveyor.yml
CMake/SMDefs.cmake
src/ProductInfo.h
src/ProductInfo.inc

This should be all the files that need to update. In game version looks right and it now create a Stepmania 5.2 folder for userdata.

Update Product version to 5.2

---

Themes/_fallback/Scripts/04 menu.lua
Themes/default/BGAnimations/ScreenOptionsTheme overlay.lua
Themes/default/Languages/en.ini

Apparently I forgot to make the actual commit and nobody told me for a week.

Actually migrate ScreenOptionsTheme to new menu system

---

Docs/credits.txt
Docs/credits_old_Stepmania_Team.txt
src/BeginnerHelper.cpp
src/BeginnerHelper.h
src/ScreenHowToPlay.cpp
src/ScreenHowToPlay.h
stepmania.nsi

The full credits for the "Stepmania Team" referenced in the credits was lost in 2009 ("remake this list"). Those people still deserve credit.
Also, my name has changed.

Restore missing legacy Stepmania Team credits

---

src/Course.cpp

Check entry id in GetCourseEntry.  Add GetNumCourseEntries.

---

extern/CMakeProject-tomcrypt.cmake

v1.16 had conflicts with latest Windows SDK headers.

Update tomcrypt to v1.18.0

---

Docs/Luadoc/Lua.xml
Docs/Luadoc/LuaDocumentation.xml
src/Model.cpp
src/Model.h

New lua function:
InverseBindPose(bool bInverseBindPose)
This allows one to enable/disable applying the inverse bind pose matrix from #983
By default, it's set to true.
This is a solution to issue #1575 .

Added a lua setting for the inverse bind pose matrix.

---

Themes/_fallback/Scripts/03 notefield_prefs.lua
Themes/_fallback/Scripts/05 noteskin_menus.lua
Themes/default/BGAnimations/ScreenGameplay in/default.lua
Themes/default/BGAnimations/ScreenGameplay overlay/default.lua
Themes/default/BGAnimations/ScreenNestyPlayerOptions overlay.lua
Themes/default/Graphics/NoteField layers.lua
Themes/default/Graphics/pause_menu.lua
Themes/default/Languages/en.ini
Themes/default/Scripts/04 player_options.lua

Forgot other people had to exit gameplay to change options.

Add player options to pause menu for changing them in gameplay.

---

src/ScreenSelectMusic.cpp

SSM needs to prune unplayable trails out of the selectable list in course mode.

SSM needs to prune playable trails.

---

src/GameSoundManager.cpp

Since random numbers have no restriction on repetition (otherwise they wouldn't be random), it is possible for announcers to repeat the same line many times in a row. To add a better variety, creating a random order for sounds to play in and reshuffling that order each time it is exhausted retains the random selection while preventing the announcer from seeming to be "stuck". With this current solution, announcers can repeat the same line at most twice in a row (if it is at the end of the order and gets shuffled to the start of the next order).

Make announcers repeat their lines less

---

.gitmodules
extern/CMakeProject-cppformat.cmake
src/RageException.h
src/RageLog.h
src/rage/RageColor.cpp

Update submodule to new fmt version, fix the code changes

---

src/ezsockets.cpp

Without this sometimes an attempt at a connection hangs and completely stops the program (VERY annoying in fullscreen) in the recv function.

Add timeout to smo sockets

---

src/CMakeData-arch.cmake

WITH_PARALLEL_PORT was added, but the list appending was not corrected.

Forgot the WITH_PARALLEL_PORT option

---

README.md

oh and fixed the formatting for the submodules section

Update all links in the README to https://

---

Themes/default/Languages/ko.ini

I've just finished translating the Stepmania Language into Korean. Although the current Korean fonts cannot show all of the possible Korean letters(which bums me out), I hope that someone convert the font (from the link I've left at the _fallback ko.ini) into image files, so that Stepmania can fully support Korean letters.

Korean translation of 'default theme.'

---

Themes/_fallback/Languages/ko.ini

I just found out that the new Korean font type's been accepted...

Korean Translation of _fallback theme

---

Themes/_fallback/Languages/ko.ini

I found some errors in my work(e.g. typos, mis-translations, inconsistencies etc.) while proofreading this, and thus decided to amend these right away.

Little Amends

---

.editorconfig

Fixes #1862.
Taken from 15c4d46.

Adjust .editorconfig
